### ISSUE TITLE
[CI] Assurance from `.travis.yml` is very low

### ISSUE THREAD

**Issue by artagnon** [coq-community/vscoq#108]
We should wire up `server/test`, `client/test` into the 'test' target, add more sanity checks, and get Travis to actually test and package every PR.

This will speed up the development process greatly, as the review burden decreases.

**Comment by maximedenes** [comment]
I agree. I would advise to focus on client tests, though, since the server part should be replaced by a Coq-side server soon.

**Comment by maximedenes** [comment]
Fixed by #384
