### ISSUE TITLE
Critical exception on Interpret To Point command in SMTCoq

### ISSUE THREAD

**Issue by ecranceMERCE** [coq-community/vscoq#114]
Hello,
I am currently playing with the [SMTCoq](https://github.com/smtcoq/smtcoq) library, interpreting code and validating proofs in VSCode with the VSCoq extension. However, I recently got into trouble several times when importing this library with the following line at the beginning of the file:
```coq
Require Import SMTCoq.SMTCoq.
```
Using **Interpret To Point** on various lemmas then outputs the two following errors:
```
Worker dies or task expired
```
```
Anomaly "cannot find D0 in module Coq.Numbers.Cyclic.Int31.Int31."
Please report at http://coq.inria.fr/bugs/.
```
To take an example, let us consider the following lemma:
```coq
Lemma foo : True.
Proof.
  exact I.
Qed.
```
If I interpret it until the `Qed.` line with an **Interpret To Point** command, the first error will occur on the `Proof.` line right after the declaration, and the second one will be located at the next line `exact I.`, which is the first line of the proof.

While finding a minimal way to reproduce the bug, I have been trying to figure out where it comes from. Here are some facts I have managed to check:
- using plain Coq without imports, or importing any other library (including external ones distinct from the standard library) does not break the extension. It means SMTCoq must have something to do with the errors ;
- interpreting the proofs line by line does not break the extension either. The only failing case is when importing a full proof, from its declaration to the `Qed.` mark, with **Interpret To Point** ;
- the corresponding Coq file compiles into a `.vo` file through `coqc` without any error or warning. Moreover, interpreting the file in a ProofGeneral environment showed no failures. It means the error seems to be also linked to VSCoq, and that is why I am opening the issue here.

I am linking a copy of the logs while reproducing the bug. One can see that when `Goal()` is called only once at the end, the error occurs, and when it is called at every line, the interpreter does not output any error.

Thanks in advance for reading!
[bug.log](https://github.com/coq-community/vscoq/files/4199385/bug.log)

**Comment by gares** [comment]
I think you should be able to reproduce the bug also doing `coqc -async-proofs on yourfile.v` and in that case please pass -debug to coqc and port the trace. The bug is probably Coq or CoqSMT related, VSCoq currently just pretends being CoqIDE, and I bet you can reproduce it with CoqIDE as well...

**Comment by maximedenes** [comment]
I can confirm that this is not a VsCoq bug. Probably it is SMTCoq trying to resolve some Coq symbols too early (at linking time). I'm transferring the issue to SMTCoq and will try to contribute a fix.

**Comment by maximedenes** [comment]
Thanks for the report! I opened https://github.com/smtcoq/smtcoq/issues/58 with a fix at https://github.com/smtcoq/smtcoq/pull/59.
