### ISSUE TITLE
customizeProofViewStyle command not found

### ISSUE THREAD

**Issue by bergwerf** [coq-community/vscoq#118]
command 'extension.coq.proofView.customizeProofViewStyle' not found.

I suspect some renaming went wrong somewhere.

**Comment by maximedenes** [comment]
@bergwerf can you elaborate on how to trigger this message?

**Comment by bergwerf** [comment]
Hmm, good question. It appears this command was removed last year: https://github.com/coq-community/vscoq/commit/ede81e630924d3627f2be6ae52f04811a9b54c5a

I may have installed my vscoq before this was released. I cannot find the command anywhere in the code here, so I assume this is no longer relevant.
