### ISSUE TITLE
Bug: closing a file and re-opening it breaks interaction

### ISSUE THREAD

**Issue by bergwerf** [coq-community/vscoq#120]
When I open a file interpret to the end, close it, and open again, then interaction is no longer working. When I press Alt + down it goes back to the file I was previously working on. If this is not reproducible I can provide an example. I use a `_CoqProject`.

**Comment by mrhaandi** [comment]
This bug is quite troublesome because clicking a file once (and interpreting a part of it) opens it temporarily and then closes it as soon as another file is clicked.
After that one cannot reopen the closed file for interaction anymore.

**Comment by bergwerf** [comment]
Double click to open a file permanently.

**Comment by TheoWinterhalter** [comment]
Or "save" (<kbd>Ctrl</kbd> + <kbd>S</kbd>) in the tab (even without having made any change).

**Comment by ljlin** [comment]
Same problem  on macOS 10.15.3 (19D76), VSCode 1.43.2, VSCoq 0.3.1 and Coq 8.9.0.
Double click or "save" does not solve this problem completely. It does work when I close a file for the first time. But the interaction stop working after I close for the sencond times and it goes back to the last file I previously closed.

**Comment by bergwerf** [comment]
@ljlin That sounds exactly like what I described. The point of save/double click is to keep the file open. If you close it, interaction is broken.

**Comment by Blaisorblade** [comment]
FWIW, keeping files open indefinitely is not a sustainable workaround — it just makes navigation impossible.

Cmd-Shift-P "Developer: Reload Window" reloads VSCode and VSCoq, fixing the VsCoq state — but then you must reprocess files in VsCoq.

**Comment by fakusb** [comment]
FYI: PR #167 does allow you to reopen a file, but probably leaks memory.

**Comment by fakusb** [comment]
And https://github.com/microsoft/vscode/issues/109749 asks for API for vscode that would allow to disable preview-mode once processing has started.

**Comment by maximedenes** [comment]
Should be closed by https://github.com/coq-community/vscoq/issues/155.
