### ISSUE TITLE
Auto-complete suggests commands in proof mode: pretty useless.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/vscoq#121]
Every time I type a space at the beginning of a new sentence (in my case it happens when indenting, i.e. at the beginning of a proof, or of a new bullet), I get auto-complete suggestions of some common Coq commands as shown in the screenshot. In proof mode, this is pretty useless and I would prefer to not see any suggestion at all, or a list of the most commonly used tactics (`intros`, `apply`, `easy`, `induction` and possibly their SSReflect counter-part if the SSReflect plugin is loaded).

![2020-03-09-172410_1920x1080_scrot](https://user-images.githubusercontent.com/1108325/76235494-77b9c300-622b-11ea-847e-ea4bfdcc126e.png)

PS: given how bad practice it is, I wish that `Global Unset` was not in the list of these common commands that are suggested when I type a space.

**Comment by maximedenes** [comment]
This behavior is new, not sure what changed it. Will investigate.

**Comment by TheoWinterhalter** [comment]
I think I had it before the update.

**Comment by maximedenes** [comment]
It seems there are two kinds of snippets provided by VsCoq: some are contributed via the standard extension point, some others are directly registered through the Snippets API. I believe we should migrate everything to the first kind.
