### ISSUE TITLE
Interrupt not working

### ISSUE THREAD

**Issue by jad-hamza** [coq-community/vscoq#123]
Hello, the `Coq: Interrupt` command doesn't seem to be working (I don't see the highlight going away when I use it, and the state seems stuck there with the fan spinning), for instance on this example:

```coq
Ltac f := f.
Goal False.
  f.
```

Using this change it's working well: https://github.com/jad-hamza/vscoq/commit/5c05900898b00abde175e5b305f4263499331af7

Edit: using Linux

**Comment by maximedenes** [comment]
Should be fixed by #127.
