### ISSUE TITLE
Cannot see the goal without scrolling

### ISSUE THREAD

**Issue by marcomaida** [coq-community/vscoq#125]
Good morning,
I just installed this extension, and I think it may be great for me. 
Right now, I have a very easy-to-solve but boring issue: since my hypotheses fill the screen, I have to scroll down to see the goal. Everytime the proof gets longer, I need to scroll down manually again. Hence, the tool is currently very painful to use.

I think an immediate solution would be to automatically scroll to bottom when the view is updated, since the goal is what I care about most of the times.

**Comment by TheoWinterhalter** [comment]
I agree this an issue! Personally I would even like to have the goal and the hypotheses in separate *scroll areas* (like I would be able to scroll the hypotheses while keeping my goal in sight).
Presumably this is much harder to implement.

**Comment by maximedenes** [comment]
This should be fixed by #130. Feel free to reopen if it is not the case. Thanks for reporting!

@TheoWinterhalter your suggestion makes sense to me, would you mind opening a specific issue?
