### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by volodeyka** [coq-community/vscoq#126]
Hello,
I've installed vscoq on my macOS (on Linux everything working) but it doesn't highlight syntax. I downloaded coq via opam and my current version is 8.11, so my coq binaries for vscoq in opam root file.
<img width="1440" alt="issue" src="https://user-images.githubusercontent.com/55004725/78469820-194e0a80-772d-11ea-9507-9eae0ca7c2cf.png">

**Comment by maximedenes** [comment]
Sorry for the lack of feedback, we are very busy these days. Did you manage to solve your issue?

**Comment by volodeyka** [comment]
Yes, I did, thanks!

**Comment by nlao1** [comment]
@volodeyka Do you mind explaining how you fixed it (if you remember)? I also have this issue.

**Comment by volodeyka** [comment]
@nlao1 Actually, I just stopped using `\lambda` :)
