### ISSUE TITLE
vscoq parser is not coping with mathcomp/algebra/interval.v notations

### ISSUE THREAD

**Issue by CohenCyril** [coq-community/vscoq#14]
```json
{
	"resource": "/home/ccohen/git/math-comp/master/mathcomp/algebra/interval.v",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "unterminated bracket '['",
	"source": "parser",
	"startLineNumber": 354,
	"startColumn": 43,
	"endLineNumber": 362,
	"endColumn": 14
}
```

Indeed vscode expects opening and closing brackets to match even if Coq parser would be ok with it, or even in comments (as @gares just showed me) !! e.g.
```coq
(* This is a smiley comment :) *)
```

**Comment by maximedenes** [comment]
For reference, another (less exotic) parsing issue in `FCF`, file `DistSem.v`, proof `evalDist_le_1`. VsCoq seems to be struggling with braces.
