### ISSUE TITLE
Publish vscoq in open-vsx.org

### ISSUE THREAD

**Issue by daniel-sousa-me** [coq-community/vscoq#146]
I installed to use [vscodium](https://vscodium.com/) instead of vscode, but because of licensing restrictions it does not have access to Microsoft's Marketplace. open-vsx.org has been created as an alternative "more open" marketplace.

Could you publish vscoq there? They have [instructions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension) for how to publish it.

**Comment by gares** [comment]
In the meanwhile you can also enable the usual marketplace and install cscoq from there. I could find how in a vscodium issue.

**Comment by daniel-sousa-me** [comment]
I have already done that ;)

But I thought it might be worthwhile to publish vscoq in the other repo as well

**Comment by gares** [comment]
Here the link to the workaround: https://github.com/VSCodium/vscodium/issues/418#issuecomment-659257713

**Comment by Zimmi48** [comment]
On Coq-Club today, @spitters mentioned https://www.gitpod.io/ as an already available Codespace alternative (i.e. it provides a ready to use VsCode environment in the browser). However, you can only install extensions available on Open VSX there. This seems like a great incentive to fix this issue.

**Comment by yannl35133** [comment]
Is it much harder to package for open-vsx than it is for Microsoft's Marketplace ?

**Comment by fakusb** [comment]
Here you go: https://open-vsx.org/extension/maximedenes/vscoq

**Comment by fakusb** [comment]
For the record for maintainers:
I added short descriptions on how to publish to the wiki https://github.com/coq-community/vscoq/wiki/Publishing
