### ISSUE TITLE
Opening proof view usually looses focus

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/vscoq#156]
When I press "Alt+down" in a Coq file, the proof view windows is opened. This usually looses focus in the main window, so that further "Alt+down" does not work. One has to click again in the main Coq window.

**Comment by TheoWinterhalter** [comment]
On which platform do you have this problem? On macOS this certainly never happened to me.
Do you still have the same problem when using "step forward" from the command palette (<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> then search "step") instead of using <kbd>Alt</kbd> + <kbd>Down</kbd>?

**Comment by thery** [comment]
@MSoegtropIMC is this still an issue?

**Comment by MSoegtropIMC** [comment]
@thery : rarely, but I can still reproduce it 100% in this way:

- open VSCode
- open a Coq Project
- close all Windows in this Coq Project
- close VSCode
- open VSCode and open the same Coq Project from "Get started" window
- open a file from the file list of the project
- now the file does not automatically have the focus, so one has to click in it
- forward - the proof view opens and the file looses focus again

AFAIR the reproduction sequence was much less contrived when I originally created the issue.

**Comment by thery** [comment]
On linux `v0.3.6`, I can't reproduce it.

**Comment by 4ever2** [comment]
I can reproduce this on both macOS and Windows. Looks like this could be a VSCode problem.

**Comment by thery** [comment]
@MSoegtropIMC  @4ever2  which version of vscode you are running?

**Comment by 4ever2** [comment]
> which version of vscode you are running?

VSCode 1.74.0 with VsCoq 0.3.6

I have a workaround which seems to work https://github.com/4ever2/vscoq/commit/4a1df3683c2ebd8efb0f1728abbae7bc892a315d.
I can open a PR later once I have tested it properly.
