### ISSUE TITLE
Shortcut for `Set Printing All.`

### ISSUE THREAD

**Issue by artagnon** [coq-community/vscoq#161]
Does a keybinding for this exist? If not, we should have one, since it's quite useful: CoqIDE has one.

**Comment by fakusb** [comment]
You can add your own shortcut at, using `F1` -> `workbench.action.openGlobalKeybindings` -> `extension.coq.display.toggle.allBasicLowLevelContents`.

Or did you mean we should provide default shortcuts?

**Comment by artagnon** [comment]
Sorry, I forgot about this; I'll add my own keybinding. Thanks.
