### ISSUE TITLE
Asynchronous evaluation of custom Vernacular with side effect 

### ISSUE THREAD

**Issue by fakusb** [coq-community/vscoq#162]
I have a problem that VSCoq does not wait for commands with side effect, causing errors when later parts depend on this sideeffect.

I use the [Smpl plugin](https://github.com/uds-psl/smpl), which is a way to write extensible tactics. It implements it's own kind of database, similar to hint DBs, to achieve that. The databases are created using the Vernac "Smpl Create $name", which is [classified as SIDEFF](https://github.com/uds-psl/smpl/blob/coq-8.12/src/smpl.mlg#L239) in the grammar.

For some reason, the following fails in asynchronous evaluation, as if the definition of test is checked without waiting for the previous command to finish.

```
Require Import smpl.Smpl.

Smpl Create newDB.
Ltac test := smpl newDB.
```

I thought that SIDEFF causes asynchronous evaluation to block.? Or am I misunderstanding the Idea behind vernacextend.mli and this is this maybe a Bug in Smpl?

**Comment by gares** [comment]
One aspect is parsing versus execution. There is a VtNow thing for commands changing the "parser" https://github.com/coq/coq/blob/516a7009b08c443a74ef7f3175fff1337e71b668/vernac/vernacextend.mli#L36 . It is usually for command like Notation, If the tactic argument for smpl does access a state updated by smpl create, then you get a problem. I did not check your parsing rules, I'm just speculating.

**Comment by fakusb** [comment]
Seems very reasonable, so I guess I can use [this parsing rule part](        - Use '... EXTEND %s CLASSIFIED BY f ...' to specify \) to implement/check that. thanks
