### ISSUE TITLE
vscoq on raspberry

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#163]
I am trying to run `vscoq` on a `raspberry pi`. I could install `coq` (version 8.9.0) directly
and I could install`vscode` (1.5.0)  + `vscoq`  extension (0.3.2) but it does not work. 
It is complaining about some `coqide` stuff not being present. 
Unfortunately I cannot install `coqide` directly, is it really needed to run `vscoq`?

**Comment by thery** [comment]
@artagnon  yep unfortunately coqidetop is not in the coq package provided by debian :disappointed:

**Comment by Blaisorblade** [comment]
since coqidetop is what provides async proofs, this is a debian bug (unless they provide an extra package for coqidetop) — do you have an upstream bug?

**Comment by Blaisorblade** [comment]
if coqidetop _is_ provided in the coqide package, you could always download the binary and carve it open as a workaround, to install by hand only coqidetop without the rest.

**Comment by thery** [comment]
unfortunately only coq and coq-theories are available : https://packages.debian.org/buster/math/

**Comment by fakusb** [comment]
You could also try installing `opam`, the ocaml packet manager, and then install Coq from there as described here: https://coq.inria.fr/opam-using.html
I will close this issue as it is not related to vscoq.

**Comment by thery** [comment]
@fakusb I've tried opam but the compilation of coq failed when compiling AVL .....

**Comment by fakusb** [comment]
Hm, you could probably open a bug report on https://github.com/ocaml/opam/issues

**Comment by thery** [comment]
@fakusb no it is just that my raspberry does not have enough memory... using the precompiled debian package would make my day ;-)
