### ISSUE TITLE
ProofView uses distracting strikeouts, or mangles the term, when something failed to unify

### ISSUE THREAD

**Issue by ezrakilty** [coq-community/vscoq#164]
When Coq fails to unify two terms, the vscoq ProofView gives me quite ugly output. It seems to be trying to "mark up" the left-hand term with some red backgrounds and strikeouts, as if to show me the diff between the two terms, but it doesn't help and just makes the term more-or-less unreadable. That much is true for the simplest cases, which I can cope with.

But in some cases, it makes real nonsense out of the term, as in the attached screenshot. It looks like a terminal that is randomly overwriting parts of previous lines. In this case, it's trying to saying something about a function called "Vector.at" but it's showing "r.ctor.at", among other problems. I'm on VSCoq 0.3.2.

![Screen Shot 2020-10-24 at 2 41 08 PM](https://user-images.githubusercontent.com/15773/97094211-9a0c1f80-1607-11eb-9879-054da0cce00c.png)

**Comment by fakusb** [comment]
I opened a PR that at least disables the strike-out if one wants to do so #166 . This probably does nothing related to the mangles r.ctor.ar .

If you still have a reproducible example, I can have a look into the exact problem.

**Comment by ezrakilty** [comment]
Great, thank you!

**Comment by fakusb** [comment]
Here is a self-contained example of this bug:

````
Require Vector Fin.
Notation " [| x ; y ; .. ; z |] " := (Vector.cons _ x _ (Vector.cons _ y _ .. (Vector.cons _ z _ (Vector.nil _)) ..)).

Lemma bug164 : { n12 & { n13 & Vector.t (Fin.t (1 +  (S (S (S n12))))) n13}}.
Proof.
  do 2 eexists. 
  exact ([|Fin.F1;Fin.L 3 (Fin.R 1 Fin.F1)|]). (*The diff-output does not make any sense*)
````
