### ISSUE TITLE
Vscoq does not indicate if queries fail

### ISSUE THREAD

**Issue by fakusb** [coq-community/vscoq#183]
vscoq does not respond in an any way if querrys made via the vscode-command fail, e.g. Checking `true + nil`.

This is different from the fact that queries with empty result (Search) are not saying that there is a query and it is empty, at least that is my impression from looking at the code.

I have no idea how to fix this, as queries via vscode in general seem very hacked.

**Comment by rtetley** [comment]
The query panel now gives feedback when a query fails.
