### ISSUE TITLE
Async proof checked in brackground causes delay in new commands

### ISSUE THREAD

**Issue by fakusb** [coq-community/vscoq#185]
Sometimes, async proofs checked in the background lead to that on a new input from the user, the current position is only evaluated after some delay. I guess that's because the number of workers is limited and we can only execute new commands once another worker finished.

It would be nice to either be able to deactivate async altogether in the settings, or to allow the user-command to execute even if that would spawn one worker too much, or both.

**Comment by TheoWinterhalter** [comment]
You can always use the command "Interpret to point (Synchronous)" if you want to deactivate async, I use it a lot.

**Comment by gares** [comment]
This must be an artefact of the conversion lsp-xml. Coq spawns by default one worker for (jumped across) proofs, while master is for all the rest.

**Comment by rtetley** [comment]
There now is an option to deactivate async I believe
