### ISSUE TITLE
incorrect goal display with Coq 8.13 beta1

### ISSUE THREAD

**Issue by mrhaandi** [coq-community/vscoq#190]
When used with `Coq 8.13 beta1` after executing the following code
```
Goal True.
Proof.
  assert False. 
```
vscoq displays two goals both of which are (incorrectly) `True`.

This was reproduced under both Widows and Linux.

**Comment by gares** [comment]
If it's only on beta1, please also open this in Coq.

**Comment by fakusb** [comment]
Fixed in https://github.com/coq/coq/pull/13662
