### ISSUE TITLE
[wish] Fallback for coqidetop.opt

### ISSUE THREAD

**Issue by gares** [coq-community/vscoq#192]
I'm preparing a [snap package for Coq](https://github.com/coq/platform/pull/49) which will contain `coqidetop.opt` but, due to snap "limitations", its name will be `coq-prover.coqidetop`.

Would it be possible to have the default executable name used by vscoq take into account this other name as well (as a fallback)?
The point is that I'd like it to work out of the box, and not have to tell users to configure this and that in vscoq.

**Comment by gares** [comment]
The snap is now ready for testing: https://github.com/coq/platform/tree/v8.13/linux/snap
I can write a patch myself, but I'd like to know if the fallback seems an acceptable idea to you.
CC @fakusb @maximedenes

**Comment by fakusb** [comment]
I think it's very acceptable.

**Comment by Zimmi48** [comment]
This isn't needed anymore now because new aliases have been added to the Snap package.
