### ISSUE TITLE
Word wrap too narrow.

### ISSUE THREAD

**Issue by Ishaangandhi** [coq-community/vscoq#197]
This is a screenshot on MacOS with the latest version of VSCoq. It doesn't happen all the time, but when it does, I can reset the word wrapping by closing and reopening the ProofView pane.

![image](https://user-images.githubusercontent.com/761037/108640820-a3d84f00-7450-11eb-90ac-f06aed0f379b.png)

**Comment by TheoWinterhalter** [comment]
This has already been reported here: https://github.com/coq-community/vscoq/issues/151
It has already been fixed in the repo, and should be coming with the next update if you don't want to install it manually.

**Comment by fakusb** [comment]
(released on marketplace)
