### ISSUE TITLE
Move document manager code to this repo

### ISSUE THREAD

**Issue by maximedenes** [coq-community/vscoq#198]
Integrate it as a branch and get rid of the submodules.

Cf https://github.com/gares/vscoq-language-server

**Comment by gares** [comment]
The more I think about it and the less I m convinced.

Fort example when we tag we tag both, but it is not clear they are coupled. Also the tarball would contain both but opam or mix only needs one.

All the pros I can see can be obtained via a submodule.

What is the motivation for this? What are the advantages over just moving the repo to coq community?

**Comment by maximedenes** [comment]
Done.
