### ISSUE TITLE
Reference not found in Elpi Coq tutorial only in VSCoq

### ISSUE THREAD

**Issue by fasapa** [coq-community/vscoq#225]
I was playing with Coq Elpi tutorial, and VSCoq throws an error: `The reference lp was not found in the current environment.` when quoting identifiers without parenthesis in Coq Elpi tutorial (lines [410-426](https://github.com/LPCIC/coq-elpi/blob/v1.9.7/examples/tutorial_coq_elpi.v#L410-L426)). The error does not appear when invoking `coqc` or in a standalone file within VSCoq:
```coq
From elpi Require Import elpi.

Elpi Command test.
Elpi Query lp:{{
  coq.say (fun `x` {{nat}} x\ {{ fun x : nat => x + lp:{{ x }} }})
}}.

Elpi Query lp:{{
  coq.say (fun `x` {{nat}} x\ {{ fun x : nat => x + lp:x }})
}}.
```

Coq 8.13.2
VSCode 1.55.2
VSCoq 0.3.4
Coq Elpi lang 0.0.4

**Comment by gares** [comment]
Also try `F1, restart extension host`.

**Comment by fasapa** [comment]
> Also try `F1, restart extension host`.

Seems to have solved the issue. I'm using elpi 1.9.7.
