### ISSUE TITLE
Coq: Reset .doesn't kill coq process

### ISSUE THREAD

**Issue by Alizter** [coq-community/vscoq#233]
Often I find myself doing something stupid:
```coq
Ltac something_stupid tac p :=
    something_stupid ltac:(something_stupid tac p) p.

Goal Type.
something_stupid idtac 0.
```
But when I run `Coq: Reset` in VSCoq, it doesn't kill the coqidetop process. I would expect it to kill the process like it does in coqide.

**Comment by TheoWinterhalter** [comment]
I think so, it's annoying to have to reload everything, because maybe you have other tabs doing other things and you don't want to reload all your extensions.

**Comment by rtetley** [comment]
Cool, will create a new issue and reference this one !
