### ISSUE TITLE
VSCoq has stopped working completely

### ISSUE THREAD

**Issue by artagnon** [coq-community/vscoq#235]
With VSCode 1.57.0-insider, an update that came in last week, the hypothesis/goals window is completely blank, making VSCoq entirely unusable. I've tried different VSCoq versions, as well as different Coq versions, and am convinced that the VSCode version is the only change.

**Comment by gares** [comment]
I confirm that with VSCode 1.57 the webview (goal window) does not work. I get this error:
```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**Comment by gares** [comment]
If you installed vscode via snap, then `sudo snap revert code` brings you back to a working revision

**Comment by sparusaurata** [comment]
Do you have an idea when then fix will be published? Just to know if it makes sense to manually revert Codium, or if I just have to ait a few days more.

**Comment by fakusb** [comment]
thanks to @swils, this is now fixed. it is in the "official"/vscode marketplace, and should also arrive in the open-vsx/codium marketplace today.

**Comment by gares** [comment]
While the fix worked nicely on 1.57.0, as soon as I upgrade to 1.57.1 the empty proof view is  back with the same error message.
CC @swils @fakusb

**Comment by gares** [comment]
(reverting back to 1.57.0 works around the issue)

**Comment by swils** [comment]
Strange, can't confirm it? Also running on 1.57.1 on OS X, version 0.3.5, with proof view still working for me... anybody else having this problem?

**Comment by sparusaurata** [comment]
> Strange, can't confirm it? Also running on 1.57.1 on OS X, version 0.3.5, with proof view still working for me... anybody else having this problem?

Same here, it works fine with 1.57.1 on Linux.
