### ISSUE TITLE
Compatibility with 8.14

### ISSUE THREAD

**Issue by fakusb** [coq-community/vscoq#240]
The changes for https://github.com/coq/coq/pull/13663 mean that vscoq does not work with 8.14 yet.

We probably need a change that just acknowledges the existance of that new field and fixes parsing, without using the name (yet?), probably involves only shifting the array subscript positions in the goal case of the doDeserialize:
https://github.com/coq-community/vscoq/blob/master/server/src/coqtop/xml-protocol/deserialize.base.ts#L436

Preferably, we do so depending on the "protocol_version " for backwards-compatibility.

**Comment by herbelin** [comment]
Informed by @mattam82, note that it would be trivial to have the new field at the end if that provides compatibility for free!

**Comment by fakusb** [comment]
That would make things free on our side, nice
