### ISSUE TITLE
How to set the coq path for vscode (how to find coqtop)?

### ISSUE THREAD

**Issue by brando90** [coq-community/vscoq#243]
I installed the extension but it does not find the path to coqtop automatically. So how do I find it?

https://stackoverflow.com/questions/71343424/how-to-tell-vscode-where-coq-is

**Comment by brando90** [comment]
I installed coq using the link given by the extension and then going here:

https://github.com/coq/platform/releases 

and clicking the mac dmg

**Comment by brando90** [comment]
related: https://coq.discourse.group/t/coqtop-not-found/856/8

**Comment by brando90** [comment]
The dmg didn't work (ie didn't find coqtop) so I installed it with opam and now vs-code was able to find coqtop by itself once I installed it with opam. Perhaps that is your issue. This is how I installed it with opam:

## Installing Coq

1) install brew: https://brew.sh/

2) install opam (https://opam.ocaml.org/doc/Install.html):
```
# Homebrew
brew install gpatch
brew install opam
```
check opam was installed:
```
opam --version
```

3) follow inria's instructions: https://coq.inria.fr/opam-using.html but I think this works:
```
opam init
eval $(opam env)

opam install opam-depext
opam-depext coq

opam pin add coq 8.13.1
```
note: Pinning prevents opam from upgrading Coq automatically, which may cause inadvertent breakage in your Coq projects

then check coq installed correctly with:
```angular2html
coqc -v
```

To ensure that installation was successful, check that 
```coqc -v```
prints the expected version of Coq.

hope it helps though I know this doesn't answer the question of "where is coqtop" which I think would be nice to get an answer.

**Comment by brando90** [comment]
though previous comment helps it doesn't actually solve the problem of finding coqtop which I think an answer should exist anyway.

**Comment by Blaisorblade** [comment]
One must fill this dialog with the path to the `bin` folder containing `coqtop` & C. This might not be necessary if `coqtop` is available in the `PATH`.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/289960/143719669-31bf8cee-3c0a-48db-90ea-d2f8b507d626.png">

**Comment by BoltonBailey** [comment]
I was given the advice to run `eval $(opam env); dirname $(which coqtop)`, which worked for me to find the right path.

**Comment by brando90** [comment]
> eval $(opam env); dirname $(which coqtop)

@BoltonBailey this didn't do anything for me. Was it suppose to change my PATH? How do I know if I did this right?

**Comment by BoltonBailey** [comment]
This command is meant to print out the right directory for you to paste into the VSCode VSCoq UI when it complains that it can't find coqtop. If it doesn't print out a directory, I presume there's a problem with coq actually being installed. If you pasted it in but still can't get it to work I'm not sure what the issue is.

**Comment by Blaisorblade** [comment]
I gave an answer in https://coq.discourse.group/t/how-to-have-vscode-fidn-coq/1582/2?u=blaisorblade, where @brando90 gave more info. Let's not spread discussion.

**Comment by brando90** [comment]
I think this should solve this: https://coq.discourse.group/t/how-to-have-vscode-find-coq/1582/2?u=brando90 going to settings and pasting the right path depending on which opam switch you are.

**Comment by brando90** [comment]
on a related issue, I had problems with coqhammer and vscode...can't figure out what the issue is... https://github.com/lukaszcz/coqhammer/issues/122

**Comment by brando90** [comment]
Ok I fixed it I think. This is what I did:

1. create a new switch opam switch create hammer_switch ocaml-base-compiler.4.12.0 and made sure I had xcode & hombrew/brew.
2. I installed the coq plataform using their binaries https://github.com/coq/platform/blob/main/doc/README_macOS.md and ran `bash coq_platform_make.sh`
updated my path with `$(opam env)`
3. made sure coqtop path in the vscode settings had the path from my PATH e.g. `/Users/brandomiranda/.opam/__coq-platform.2022.01.0~8.15~beta1/bin` or do `echo $PATH` copy the coq part into vscode's setting
4. restarted vscode several times to make sure it was running the above path.



----

related but when installing new plugin: https://github.com/lukaszcz/coqhammer/issues/122

vscode gitissue: https://github.com/coq-community/vscoq/issues/243
