### ISSUE TITLE
Invalid characters in file name break highlighting globally

### ISSUE THREAD

**Issue by benrbray** [coq-community/vscoq#245]
Thanks for this great extension!  I encountered some strange behavior where the extension can't recover when coqtop fails and is restarted.  Here's how I arrived at the issue:

* Create a new file with an invalid name like "bad-bad.v".  Enter a theorem or two.
* Try to step through a proof with Alt+Down.  The output panel will show an error like `coqtop-stderr: Error: Invalid character '-' in identifier "bad-bad".`, as expected.
* Rename the file to something valid like "good.v".  After this, you'd expect everything to be fine.
* Now, using Alt+Down will successfully step through the file, and the ProofView works normally.  However, the file itself won't have any of the usual green highlights to indicate progress.

After this happens, other perfectly valid files in the workspace will also fail to show highlights in the editor.  
Restarting VS Code resolves the issue.

**Comment by fakusb** [comment]
This is related to the problem in #188.

**Comment by rtetley** [comment]
Closing in favour of #188
