### ISSUE TITLE
Output from Ltac not Visible (e.g. 'idtac')

### ISSUE THREAD

**Issue by benrbray** [coq-community/vscoq#246]
I'm quite new to Coq so forgive me for any misconceptions I might have.  Consider the following, taken [from here](https://coq.github.io/doc/v8.12/refman/proof-engine/ltac.html#match-with-holes-ex):

```coq
Goal True.
match constr:(fun x => (x + 1) * 3) with
| fun z => ?y * 3 => idtac "y =" y; pose (fun z: nat => y * 5)
end.
Admitted.
```

Other editors print the message `y = (z + 1)` when stepping through the proof, but I don't see any output at all in vscoq.  I would expect the output to appear in the same "Output" panel that `Check` etc. print to.  I checked the available `Coq:` commands, but didn't notice anything useful. 

Is there currently a way to view these Ltac output messages in vscoq?  If not, might it be easily added?  With some guidance on where to start I might be willing to make a PR.  Thanks!

**Comment by fakusb** [comment]
You can, on the top-right of the output-panel, select "info", there this output is shown.
