### ISSUE TITLE
Infinite "Coq Loading" on startup

### ISSUE THREAD

**Issue by bcpierce00** [coq-community/vscoq#249]
I managed to get VsCoq installed on the latest vscode from a few days ago (after some trouble -- I had omitted the / at the end of the coqtop path -- might be a good idea to supply one if missing!), but when I load a .v file I see "Loading Coq" in the status line forever.  

(1) How might I fix this?
(2) How could I have investigated further for myself?

I'm running Coq 8.13.2, macOS 11.5.2, and vscode 1.60.0.

**Comment by swils** [comment]
For me personally, I make a fresh OPAM switch per project, and I put something along the following lines in the VSCode config for the project (`.vscode/settings.json`):

```
{
  "coqtop.binPath": "/Users/swils/Code/myproject/_opam/bin"
}
```

So at least in my case, there is no need for "/" at the end of the path... Then, to start VSCode, I type:

```
$ eval $(opam env)
$ code .
```

When I open a `.v` file, the extension is loaded. This can be inspected in the Coq Language Server output (typically Shift+Cmd+U on Apple, under "Coq Language Server").

**Comment by bcpierce00** [comment]
Thank you, Stefan!
