### ISSUE TITLE
Bad interaction with bracket colorization: keywords are colorized inside identifiers

### ISSUE THREAD

**Issue by julesjacobs** [coq-community/vscoq#250]
When bracket colorization is turned on ("editor.bracketPairColorization.enabled": true), the `match` and `end` keywords are colored inside identifiers. This behaviour does not happen in e.g. Ruby where `begin ... end` is used to delimit blocks.

![image](https://user-images.githubusercontent.com/476654/132466230-da6ab499-109f-4182-b582-a440f29e32b1.png)

**Comment by swils** [comment]
Seems to be related to a new feature in VSCode: colorized brackets. Made a pull request that I think solves the issue.
