### ISSUE TITLE
Inconsistent state: Can only add a comand to the current focus

### ISSUE THREAD

**Issue by qcfu-bu** [coq-community/vscoq#253]
When working with long files (over 1500 lines of code), I often encounter instances where vscoq refuses to step through the proof. Neither stepping one line at a time nor step to point works. An error message `Inconsistent state: Can only add a comand to the current focus` is displayed. I know that coq works correctly on my machine because proof general in emacs does not exhibit such an issue.

**Comment by fakusb** [comment]
Can you describe which kind of behaviour/usage leads to that error?

Did you use 'search/replace' or another editor feature that changed the document anywhere else than at the current cursor?
Does the error persist after reloading the file? (for example via 'F1 -> reload window')

**Comment by qcfu-bu** [comment]
Now that you mention it, it might be caused by edits made by the "find replace" for search and replacing string. I also sometimes revert the file to a previous version using git. 

So vscoq's internal coq process does reset its state when edits are made using these methods?

**Comment by qcfu-bu** [comment]
fixed by vscoq2
