### ISSUE TITLE
Broken with Coq master: XML protocoll change

### ISSUE THREAD

**Issue by fakusb** [coq-community/vscoq#261]
> Starting VSCode on a file in the current Coq master raises:
> 
> ```
> coqtop-stderr: [pid 41008] Unexpected XML message
> [pid 41008] Expected XML node: int
> [pid 41008] XML tree received: <bool val="false"/>
> ```
> 
> I suspect a change in the XML protocol 

https://github.com/coq/coq/issues/15282

**Comment by fakusb** [comment]
Here a backwards-compatible fix. I will create a merge request once it is tested a bit.
https://coq.zulipchat.com/#narrow/stream/237662-VsCoq-devs.20.26.20users/topic/VSCode.20and.20Coq.20master/near/264371039

**Comment by fakusb** [comment]
fixed in #262

**Comment by Blaisorblade** [comment]
For reference, this is needed starting with Coq 8.15(+rc1).
