### ISSUE TITLE
Splitting the right pane into two horizontals panes, one to show goals and other to show responses

### ISSUE THREAD

**Issue by mukeshtiwari** [coq-community/vscoq#271]
I am wondering if it is possible to break VSCode pane in a similar way to Emacs, see the picture. Right now, when we search any lemma, it opens a pane in the bottom, but it would be nice it is possible to do it in Emacs way. 
<img width="1920" alt="Screenshot 2022-02-09 at 15 35 31" src="https://user-images.githubusercontent.com/1135077/153235886-8a766818-c5df-4abf-8e7b-a6570e018804.png">

**Comment by dlesbre** [comment]
Related PR #320

**Comment by rtetley** [comment]
There is now a messages section in the goal panel
