### ISSUE TITLE
Remove mentions of hoq(ide)top

### ISSUE THREAD

**Issue by Blaisorblade** [coq-community/vscoq#272]
This is a minor cosmetic thing, but `hoqtop` is deprecated (see https://coq.zulipchat.com/#narrow/stream/240550-Dune-devs.20.26.20users/topic/Dune.20internals.3A.20build.20a.20target.20.60--only-deps.60/near/272321800). Those names are probably arbitrary anyway...

**Comment by rtetley** [comment]
I don't believe this happens in VsCoq 2
