### ISSUE TITLE
Shortcut for CoqIde `Compile` => `Compile Buffer`

### ISSUE THREAD

**Issue by gabrielle-ohlson** [coq-community/vscoq#277]
What is the shortcut/command name for compiling a buffer in vscoq (as one would do with `Compile Buffer` in CoqIde's toolbar)?  I can find the `interpret` commands, but I am unsure how to compile the `file.v` to produce a `file.vo` etc.

Thanks!

**Comment by artagnon** [comment]
As far as I know, there are no build commands available in VSCoq. I personally just hit `make` or `dune build` in the integrated terminal in VSCode.

**Comment by rtetley** [comment]
I am closing this for now as it feels like the proposed solution works well enough.
