### ISSUE TITLE
Add thread count parameter for parallel proofs

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/vscoq#284]
As discussed here [Zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Splitting.20CoqIDE.20.28options.20to.20coqidetop.29) one can get a very considerable speed up in proof checking by passing `-async-proofs-j <some value>` to coqidetop. This has been verified in release (0.3.6) VsCoq by setting `"coqtop.args": ["-async-proofs-j", "12"]` in `settings.json`.

As far as I know just passing `-async-proofs on` has the effect that one can directly navigate to a proof without checking upstream proofs, but upstream proofs are checked sequentially. When setting `-async-proofs-j <some value>` the upstream proofs are checked in parallel, which gives a speed up pretty much proportional to the thread count (except if one proof takes much longer than others and doesn't use the `par:` goal selector). The only issue is that one needs sufficient RAM.

I would suggest to add an UI accessible "Parallel proof threads" option, noting that one should have around 2GB of RAM per thread leaving 4GB for the system (of course this depends on the specific developments - some need substantially more). One should also mention, that memory consumption is proportional to the number of active files times the number of threads. So one needs to be careful with this, but properly used this feature can be great time saver, especially in restructuring work.

I have the impression that this great feature somehow went into oblivion - having this option as VsCoq UI setting might make a broader audience aware of it.

**Comment by MSoegtropIMC** [comment]
P.S.: I would set the default to one or leave it away.

**Comment by rtetley** [comment]
This is done in vscoq2: #393
