### ISSUE TITLE
Output of "Search" inconvenient.

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/vscoq#288]
Unlike CoqIDE, VsCoq appends the result of Search to previous Search results. I tested if this is an advantage or not, but in the end it turns out that before every Search I clear the "Notices" buffer.

Also this is a bit inconsistent with Print and Check - their result goes to the "Queries" buffer - which is reset each time. I would think a Search is also a query, so the result should go to the "Queries" buffer - and reset it.

Another option would be to append, but to insert a well visible separator line, preferably stating the Search command. Also the Notices buffer should be auto scrolled to end then.

Btw.: I am missing a "Search" keyboard shortcut.

**Comment by maximedenes** [comment]
I vaguely recall that the current behavior was asked by some users, maybe @thery ? I may be completely wrong.

**Comment by thery** [comment]
Nop. I don't like this behavior either. After a search I often clean the message window and rerun the search to know what the exact answer to the Search is.

**Comment by maximedenes** [comment]
Ah ah, so maybe we actually requested the same change as @MSoegtropIMC :)

Sorry for the confusion!

**Comment by TheoWinterhalter** [comment]
The `Coq: Prompt Search` command does reset the window each time. Same for `Coq: Search`.

**Comment by MSoegtropIMC** [comment]
@TheoWinterhalter : thanks - I didn't see the `Coq: Search` command - one of these nice macOS features to hide scrollbars ...

**Comment by MSoegtropIMC** [comment]
@maximedenes : I would say if this is controversial one can add a configuration option.

I think I could also live with append (in rare cases it is even useful), but then, as noted above, with a clear separator line in the results.

**Comment by thery** [comment]
Me I always do `Search` with the `Search` command in the script. A dedicated window like the `Query Panel` in coqide would be nice. Is there some tutorial that explains how we could modify `vscoq`  to do that?

**Comment by MSoegtropIMC** [comment]
Btw.: the VsCoq "Coq: Search" command outputs to the "Queries" page, while an in script search command outputs to the "Notices" command. I guess this is the reason why the VsCoq "Coq: Search" command clears the output before - all output to the "Queries" page does this.

This is a bit inconsistent.

**Comment by rtetley** [comment]
I believe the messages section in the goal panel of VsCoq 2 somewhat solves this issue. I'll close it here and if something else comes up we can continue the conversation in a different issue.
