### ISSUE TITLE
First user feedback after a few minutes when stepping into large file

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/vscoq#290]
When stepping into the Pff.v file here (https://gitlab.inria.fr/flocq/flocq/-/tree/master/src/Pff) - it is self contained, so you can just try - I don't get any user feedback for minutes.

That parsing takes a few minutes is fine - the file is huge and CoqIDE is not better in this - but CoqIDE gives visual feedback from the first second, while one doesn't get any feedback at all for minutes in VsCoq. Not even the proof view Window opens.

**Comment by MSoegtropIMC** [comment]
P.S.: my stop watch says it is 3 minutes 13s (on a i9 Mac).

**Comment by rtetley** [comment]
I'm busy writing the 2024-2025 road map for VsCoq and so also triaging my issues. This seems much better with the new version of VsCoq. First interaction happens within 2-3 seconds after opening the file. Much faster then 3 minutes ! Can I close this ?

**Comment by MSoegtropIMC** [comment]
It is indeed very fast now (I would say much less than 1s). I tested with VSCoq 2.2.1 and Coq 8.20. I am closing this issue.
