### ISSUE TITLE
Missing color for "Instance" and "Context" keyword

### ISSUE THREAD

**Issue by dlesbre** [coq-community/vscoq#298]
Coq "Context" and "Instance" keywords are not colored like other keyword (e.g. "Variable" and "Definiton").

Also of note : the brackets for record/instances `{|` and `|}` aren't colored properly, only the brace is colored, and not the vertical bar.

**Comment by SkySkimmer** [comment]
Those aren't especially builtin though

**Comment by dlesbre** [comment]
No, but they are part of the standard library and can be used without any `Import`.
