### ISSUE TITLE
Getting set up as a developer instructions, simply doesn't work on Windows 10 / MSYS

### ISSUE THREAD

**Issue by enjoysmath** [coq-community/vscoq#307]
At first I needed npm, which I installed using the Node.js binary installer today.

Now, make is available in the MSYS terminal but not on the Windows cmd.

Vise versa, npm is available in the Windows cmd but not the MSYS terminal.

So I copied the C:\msys64\usr\bin path to my Path env var in my computer's settings, so that cmd would have access to make.  But now, running make in this project's directory gives:

```
C:\Users\fruit\OneDrive\Desktop\vscoq>make
npm install
/bin/bash: C:/Program Files/nodejs/npm: No such file or directory
make: *** [Makefile:8: node_modules] Error 127
```

I verified that yes, npm is indeed present at the printed out location that supposedly didn't exist.  Could it be because of the space char in "Program Files"?

**Comment by enjoysmath** [comment]
Okay, it seems like this project is missing a node_modules directory.   What are the new build instructions?

**Comment by artagnon** [comment]
npm install.

**Comment by enjoysmath** [comment]
Yo, that works or seems to be working!!  Thank you <3

:D

**Comment by enjoysmath** [comment]
Okay, so what does that do exactly?   Will it put it into my VSCode
instance as an extension?

I might want to modify this extension.

**Comment by artagnon** [comment]
No, npm install merely fetches the listed dependencies to node_modules. You’re free to modify the extension as you see fit.

**Comment by enjoysmath** [comment]
@artagnon How does one test out the extension?  I see no VSIX file

**Comment by artagnon** [comment]
Run make to get the vsix.

**Comment by enjoysmath** [comment]
C:\Users\fruit\OneDrive\Desktop\vscoq>make
npm run compile
/bin/bash: C:/nodejs/npm: No such file or directory
make: *** [Makefile:11: compile] Error 127

@artagnon

**Comment by artagnon** [comment]
npm is supposed to be installed in C:\nodejs. Can you create a copy?

**Comment by enjoysmath** [comment]
It is.  10 minutes ago I removed it with Node.js installer and then with
the same installer, re-installed it to c:\nodejs.

**Comment by enjoysmath** [comment]
@artagnon  would you like to TeamViewer (RDP) into my machine and have a look?

**Comment by artagnon** [comment]
I’m not sure that would help, as I’ve never used MSYS, and am not on Windows. Sorry.

**Comment by enjoysmath** [comment]
Found this:
https://devblogs.microsoft.com/cppblog/now-announcing-makefile-support-in-visual-studio-code/

I will try it out.

**Comment by enjoysmath** [comment]
Tried it.  Exact same thing

**Comment by enjoysmath** [comment]
Okay, got it to work.  The only place I got it to work was (not cmd, not MSYS terminal): Git Bash installed with Git for Windows.

And it produces a VSIX after running:
`./node_modules/.bin/vsce package`

in the bash terminal.
