### ISSUE TITLE
VSCoq extension for VSCode doesn't work.

### ISSUE THREAD

**Issue by grandehe4rt** [coq-community/vscoq#333]
I think i should start making clear what i already tried, so...

* I'm on Arch Linux (x86_64)
* Coq 8.16.1 is already installed
* coqtop works properly on terminal
* coqide runs properly when launched from terminal/gnome icon
* coq bin path is at /usr/bin
* vscoq required bin path is properly configured too, i set to "/usr/bin" 
* installed coq using `yay -S coq`
* and also `opam install coq`

Everything above i already tried, installing, reinstalling and everything, but, vscoq doesn't work when i try to use any feature.

What can i do to make vscoq work?

**Comment by thery** [comment]
@grandehe4rt  Did you solve your problem?

**Comment by Blaisorblade** [comment]
Solved in https://coq.zulipchat.com/#narrow/stream/237662-VsCoq-devs-.26-users/topic/VSCoq.20extension.20for.20VSCode.20doesn't.20work — autodetect didn't pick up Coq mode.
