### ISSUE TITLE
Error message location messed up in the presence of CRLF

### ISSUE THREAD

**Issue by 4ever2** [coq-community/vscoq#339]
For files with CRLF line endings VsCoq computes error locations incorrectly.

With Coq `<= 8.14` the error start location is one character off if there is at least one `\r` in the sentence.
With Coq `>= 8.15` the error start location is off one character for each `\r` in the sentence.

**Comment by thery** [comment]
is it a `coq` issue or a `vscoq` one?

**Comment by 4ever2** [comment]
The behavior observed with `>= 8.15` is a `vscoq` issue, likely due to https://github.com/coq/coq/pull/14767.

Before `8.15`, coq would remove `\r` from XML input, so `vscoq` compensates for that when converting offsets to potions. The code doing this conversion is:
https://github.com/coq-community/vscoq/blob/146c267e511dc58581a358286e778d4acd195e0b/server/src/util/text-util.ts#L218

**Comment by thery** [comment]
why is it not simply
```
    currentOffset+= match[0].length;
    offset -= match[0].length;
```
?

**Comment by thery** [comment]
still I don´t  understand why the error is one character independently of the number of lines

**Comment by 4ever2** [comment]
> why is it not simply
> 
> ```
>     currentOffset+= match[0].length;
>     offset -= match[0].length;
> ```
> 
> ?

That would probably work for `coq >= 8.15.0` but not for older versions.

**Comment by thery** [comment]
I've tried with 8.13 and 8.16 it both seems to work

**Comment by thery** [comment]
no it works only with 8.16

**Comment by 4ever2** [comment]
The off-by-one error with Coq 8.14 and earlier seems to be a Coq issue.
Given the statement `\r\n\r\n\r\nTest a.`, Coq will return an offset of `4`, which is clearly wrong.
https://github.com/coq/coq/pull/14767 states that Coq removes carriage return by converting `\n\r` to `\r`. This would explain why Coq returns an offset `4` since the sentence would be transformed to `\r\n\n\nTest a`.

**Comment by thery** [comment]
What I don´t understand is that the fix of  `vscoq` seems to count `\r\n` as one. So the deviation could be more than one if you give 
`\r\n\r\nCheck  1 \r\n\r\n + foo.`

**Comment by 4ever2** [comment]
The deviation of the error start position cannot be more than one since the second `\r` left would be after the offset.
But in you example the error end position would be two characters off.

**Comment by thery** [comment]
the error is that `foo` is not defined so we have a shift of 2.

**Comment by 4ever2** [comment]
The obvious fix would be to change the regex to to look for `\n\r`, but I'm unsure if that would break something else.

**Comment by thery** [comment]
I think we should make the chance  
```    currentOffset
offset -= match[0].length;
````
to make the error for window works for coq >= 8.15

**Comment by 4ever2** [comment]
But doesn't that make the problem worse for coq <= 8.14?

I implemented a different fix for the coq >= 8.15 problem in https://github.com/4ever2/vscoq/commit/33eead014f4c65b46750c52a904d50394b481e0d but your fix is definitely cleaner.

**Comment by thery** [comment]
This seems to work for <= coq 8.14

**Comment by 4ever2** [comment]
Yes, that seems to work well.

**Comment by thery** [comment]
I have only two worries: 
- I am testing this on linux doing a sed to turn my linux file into a window one. I would like to be sure it works on native windows.
- The function (..CLN) that is modified is called at 2 places: STM and State.
Does your change on STM should also be reflected in State?

**Comment by 4ever2** [comment]
> I am testing this on linux doing a sed to turn my linux file into a window one. I would like to be sure it works on native windows.

I tested this on Windows. Instead of using sed you can also force VS Code to use CRLF when testing.

> The function (..CLN) that is modified is called at 2 places: STM and State.

I tried changing it in State and couldn't observe any difference, so I am unsure what should be done there.

**Comment by thery** [comment]
One of them seems about warning. So for example deprecation is a warning. In 8.14,
```coq
\r\n\r\n\r\nHint Resole id.
```
the location seems ok?

**Comment by 4ever2** [comment]
Warnings don't contain error locations so I don't think that code is reachable.

**Comment by Blaisorblade** [comment]
> Warnings don't contain error locations so I don't think that code is reachable.

Maybe that _is_ true, but warnings contain warning locations so that sounds strange — shouldn't positions be adjusted the same way?

Either way problems seem to remain. On VsCoq master (plus #319) with Coq 8.16, CRLF line endings, this code:

![image](https://user-images.githubusercontent.com/289960/218136855-af125761-6a91-439b-b146-79d011b0fcde.png)

seems to have an off-by-2 on the error but not the warning:
![image](https://user-images.githubusercontent.com/289960/218137068-64f0a6e5-740b-4bff-9f02-202aa1d6d8f5.png)

I'm (tentatively) reopening.

**Comment by Blaisorblade** [comment]
Really, the warning is off-by-one since highlighting starts at the line end, but that happens without CRLF as well so _that_ is probably separate. (I haven't compared what Coq does and/or other IDEs).

**Comment by 4ever2** [comment]
The warning is off-by-one since warnings don't seem to contain locations ([they only contain state ID](https://github.com/coq/coq/blob/master/dev/doc/xml-protocol.md#feedback-message)) so VsCoq will highlight the entire sentence.

Strangely, the error message in your example is correct on my machine with CRLF and coq 8.16.

**Comment by thery** [comment]
>> Strangely, the error message in your example is correct on my machine with CRLF and coq 8.16.
me too

**Comment by thery** [comment]
But the red means it is an error underline means it is an error

**Comment by Blaisorblade** [comment]
After pulling I agree, my bad!
