### ISSUE TITLE
Add VsCoq1-like key bindings

### ISSUE THREAD

**Issue by maximedenes** [coq-community/vscoq#351]
extension.coq.query.about
extension.coq.query.search
extension.coq.query.check

extension.coq.query.locate
extension.coq.query.print
extension.coq.stepForward
extension.coq.stepBackward
extension.coq.interpretToPoint
extension.coq.interpretToEnd

**Comment by rtetley** [comment]
- [ ] extension.coq.query.about
- [ ] extension.coq.query.search
- [ ] extension.coq.query.check

- [ ] extension.coq.query.locate
- [ ] extension.coq.query.print
- [ ] extension.coq.stepForward
- [ ] extension.coq.stepBackward
- [ ] extension.coq.interpretToPoint
- [ ] extension.coq.interpretToEnd
