### ISSUE TITLE
Declaration Provider for VsCoq2

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [coq-community/vscoq#380]
A declaration provider would make it possible to navigate to the implementation of declarations in Coq.
VsCode has a registration for them <https://code.visualstudio.com/api/references/vscode-api#DeclarationProvider>

We have a draft implementation on <https://github.com/Duckapple/vscoq/tree/vscoq2-itu-develop>

**Comment by rtetley** [comment]
Closing in favour of #214
