### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by gares** [coq-community/vscoq#39]
I'm getting a bunch of these in the output panel even if I'm *not* opening any .v file (I'm in a latex project)
```
[Error - 10:24:51 AM] >>> (node:12959) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/gares/coqws19/_CoqProject'
[Error - 10:24:51 AM] >>> (node:12959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8526)
```
Indeed there is no _CoqProject file here. I guess a "catch" is missing.

**Comment by maximedenes** [comment]
It seems that this bug can be reproduced by:
- opening both a Latex and a `.v` file
- launching Coq on the `.v` file
- building the latex file using ctrl+alt+b
