### ISSUE TITLE
Can not open proof view

### ISSUE THREAD

**Issue by speedcell4** [coq-community/vscoq#41]
none of my "open proof view" and "open proof view in external browser" works.

the settings look like below,

```
    "coqtop.binPath": "/usr/local/bin/coqtop",
    "coq.loadCoqProject": false,
    "coq.autoRevealProofStateAtCursor": true,
    "coq.editor.indentAfterBullet": "indent",
```

any idea about how to fix this?

**Comment by maximedenes** [comment]
What does the webview developers tool report? https://code.visualstudio.com/api/extension-guides/webview#inspecting-and-debugging-webviews

**Comment by speedcell4** [comment]
I even can not open the webview developers too

**Comment by Lesenr1** [comment]
Hello
Same problem for me

**Comment by maximedenes** [comment]
I'd need to reproduce the issue. Can you describe what your OS and VSCode versions are, and what steps you followed to install Coq and VsCoq? Thanks!

**Comment by speedcell4** [comment]
### OS

macOS Mojave 10.14.6

### VSCode

```bash
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

### Coq

I installed Coq by `brew install coq`

###  VsCoq

I clicked install button to install VsCoq in extension marketplace. About the VsCoq setting, I set `coqtop.binPath` to `/usr/local/bin`.

**Comment by speedcell4** [comment]
`shift + command + P` and then `coq: open proof view` but nothing happens

**Comment by kmyk** [comment]
I have the same problem. Nothing happens with `Coq: open proof view` and no error logs are generated.

By the way, I found an error message like below. This appears opening `.v` files, without `Coq: open proof view`. I suspect `vscode.previewHtml` is wrong.

``` js
[2019-08-25 19:01:34.537] [renderer1] [error] command 'vscode.previewHtml' not found: Error: command 'vscode.previewHtml' not found
    at Proxy._tryExecuteCommand (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3192:713)
    at r.then.i (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3192:594)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

https://code.visualstudio.com/updates/v1_33#_removing-the-vscodepreviewhtml-command

## Environment

It seems my environment differs from one of @speedcell4, so I describe my environment to help to reproduce the issue.

### OS

Ubuntu 18.04 LTS

### VSCode

I use the `.deb` package distributed at https://code.visualstudio.com/Download

```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic
```

Also `1.36.1` reproduces this issue.

### Coq

version `8.6`, installed by `apt install coq`

### VsCoq

I installed VsCoq following the instructions at https://github.com/siegebell/vscoq/wiki/Setup

```
Name: VSCoq
Id: siegebell.vscoq
Description: An IDE for the Coq Proof Assistant
Version: 0.2.7
Publisher: siegebell
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=siegebell.vscoq
```

The setting file `~/.config/Code/User/settings.json` is empty `{}`.

**Comment by maximedenes** [comment]
You are running an outdated version of the extension. I suggest you wait for a marketplace release. See #7.
