### ISSUE TITLE
[VsCoq2] Loading library fails

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [coq-community/vscoq#415]
Using require to load a library fails currently.

Having 2 files with one using `Require Import X.` is enough for it to fail.

This is the stack trace I get from trying to import `Basic` from `Other.v`.
```
Compiled library Whatever.Basic (in file /home/hjadal/code/ProVe/ex1/Basic.vo) makes inconsistent assumptions over library Coq.Init.Notations
Raised at Exninfo.iraise in file "coq/clib/exninfo.ml", line 79, characters 4-11
Called from Library.intern_mandatory_library in file "coq/vernac/library.ml", line 301, characters 4-181
Called from Stdlib__Array.fold_left in file "array.ml", line 163, characters 9-30
Called from Library.intern_library_deps in file "coq/vernac/library.ml", line 294, characters 4-104
Called from Library.intern_library in file "coq/vernac/library.ml", line 290, characters 21-90
Called from Library.rec_intern_library in file "coq/vernac/library.ml", line 307, characters 16-77
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from Library.require_library_syntax_from_dirpath in file "coq/vernac/library.ml", line 420, characters 25-114
Called from Synterp.vernac_require_syntax in file "coq/vernac/synterp.ml", line 384, characters 2-67
Called from Synterp.synterp in file "coq/vernac/synterp.ml", line 456, characters 6-44
Called from Dm__Document.parse_more in file "dm/document.ml", line 494, characters 14-68
Called from Dm__Document.parse_more in file "dm/document.ml" (inlined), line 511, characters 2-40
Called from Dm__Document.validate_document in file "dm/document.ml", line 567, characters 24-63
Called from Dm__DocumentManager.validate_document in file "dm/documentManager.ml", line 225, characters 30-71
Called from Dune__exe__LspManager.textDocumentDidOpen in file "vscoqtop/lspManager.ml", line 143, characters 11-50
Called from Dune__exe__LspManager.dispatch_method in file "vscoqtop/lspManager.ml", line 359, characters 30-56
Called from Dune__exe__Vscoqtop.loop.loop in file "vscoqtop/vscoqtop.ml", line 30, characters 21-50
Called from Dune__exe__Vscoqtop.loop in file "vscoqtop/vscoqtop.ml", line 35, characters 6-15
```
 
It was compiled by this `_CoqProject` and with the Coq version used as submodule:
```
-R . Whatever
Basic.v
Other.v
```

**Comment by gares** [comment]
I believe @maximedenes already investigated this bug, and even pushed a fix to the coq submodule.
Can you confirm you did `git submodule update && make` before testing?

**Comment by Hjaltesorgenfrei** [comment]
Yeah it did seem like he was working on it, also why I unassigned myself again.
I have coq checked out at 0e7dccb42d, which seems to be the version tracked on the main branch. 
Is the fix in the PR here: https://github.com/coq/coq/pull/17269

**Comment by maximedenes** [comment]
I'm not aware of such a bug, actually. The Coq PR does improve the handling of `Require` but rather in terms of performance. Are you 100% sure that `/home/hjadal/code/ProVe/ex1/Basic.v` was compiled with the version of Coq included in the submodule?

**Comment by Hjaltesorgenfrei** [comment]
I just tried to `opam install .` it again, and the behavior is still the same.
```shell
$ coqc -v
The Coq Proof Assistant, version 8.18+alpha
compiled with OCaml 4.14.0
```

**Comment by maximedenes** [comment]
I'll rebase over the Coq PR, just in case.

**Comment by maximedenes** [comment]
I opened https://github.com/coq-community/vscoq/pull/417, can't do more now (holidays here).

If the problem persists, it would be good to check it can be reproduced by someone else using an opam setup (@gares ?).

**Comment by Hjaltesorgenfrei** [comment]
https://gitlab.mpi-sws.org/iris/stdpp also fails when trying to load.
Opening any of the files containing imports gives a `makes inconsistent assumptions over library` error.

I build it by using the following commands.
```sh
$ coq_makefile -f _CoqProject -o Makefile
$ Make
```
Opening any file in stdpp folder will then give errors.

**Comment by gares** [comment]
I've updated ci since, please take a look at the last two jobs, one is using installed coq/vscoqtop.

**Comment by Hjaltesorgenfrei** [comment]
I followed the the steps in the `install-opam` target, but after a `make clean && make` i still get `makes inconsistent assumptions over library` errors.

**Comment by Hjaltesorgenfrei** [comment]
Never mind I was loading a version made by `make world` and not opam which is why I had the issue. 
vscoq.path was hardcoded to my build folder
