### ISSUE TITLE
[Vscoq1]Locations of error messages are wrong with Utf8

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#420]
It shows the wrong location 
```coq
From Coq Require Import Utf8.

Check ∀ x : 1, True.
````

**Comment by rtetley** [comment]
@thery Could you tell me what the expected behaviour is so I can check if this works in VsCoq 2 ?

**Comment by thery** [comment]
![ddd](https://github.com/coq-community/vscoq/assets/6795190/963f5527-375a-46d1-bfba-d06d497b4c83)


in vscode 1, the error is not shown on 1.

**Comment by rtetley** [comment]
Fixed in VsCoq 2, see #664
