### ISSUE TITLE
[vscoq1] "coqtop is not running" due to unsupported ipv6

### ISSUE THREAD

**Issue by Heersin** [coq-community/vscoq#442]
## issue
Running coq program in vscode with vscoq plugin, it keeps reporting coqtop is not running. the log of coq-lsp is as follows :
```sh
Coqtop binPath is: /usr/bin/
starting coqtop
exec: /usr/bin/coqtop -v
Listening at ::1:44359
Listening at ::1:40015
Listening at ::1:33795
Listening at ::1:42671
Detected coqtop version 8.16.1
Coqtop version parsed into semver version 8.16.1
exec: /usr/bin/coqidetop.opt -main-channel ::1:40015:44359 -control-channel ::1:33795:42671 -async-proofs on -Q . LF -topfile file:///home/proof/coq/example1.v
coqtop started with pid 219504
coqtop-stderr: Error: host:portr:portw or stdfds expected after option -main-channel

coqtop exited with code: 1
onCoqClosed(coqtop closed with code: 1)
onCoqClosed(undefined)
coqtop closed with code: 1
Listening at ::1:33743
Listening at ::1:34573
Listening at ::1:35201
Listening at ::1:34915
```

## environment informations
- The Coq Proof Assistant, version 8.16.1 compiled with OCaml 4.12.1
- vscoq 0.3.8
- coq-lsp 0.1.4
- node 19.7.0

## possible solution
It may due to the node js issue (after v17) https://github.com/nodejs/node/issues/40537, possible ad-hoc ways to solve it:

1. waiting for coqide to support ipv6 channel
2. use node v16 or specify node option [--dns-result-order](https://nodejs.org/api/cli.html#--dns-result-orderorder) to `--dns-result-order=ipv4first` by setting environment variable : `export NODE_OPTIONS=--dns-result-order=ipv4first`.
3. if it still prefer to ipv6 for 'localhost', you may encounter the problem caused by system preference (https://stackoverflow.com/a/74216410/14456451). for example, I have a typo in my /etc/hosts `127,0,0,1 localhost`, and thus it never route localhost to ipv4.

**Comment by Heersin** [comment]
May I ask what's the proper way to modify the code, which could specify the server to resolve localhost as ipv4 ? I have two preliminary ideas :
1. 'localhost' -> `127.0.0.1`, may not be a recommend way I guess
2. specify using `dns.setDefaultResultOrder('ipv4first')`

**Comment by 4ever2** [comment]
VS Code uses a bundled version of node, which for the most recent release is `v16.14.2`. So this shouldn't be related to v17 changes.

**Comment by Heersin** [comment]
> VS Code uses a bundled version of node, which for the most recent release is `v16.14.2`. So this shouldn't be related to v17 changes.

yep, it did use a bundled node. It was caused by my incorrect configuration.

**Comment by thery** [comment]
would be nice for us to know if this solves your problem before doing the release

**Comment by HaoYang670** [comment]
It doesn't make sense to let users do CI test for u, does it?

**Comment by thery** [comment]
as you prefer, it is your choice

**Comment by Agnishom** [comment]
I am trying the command you suggested above, and I am getting an error:

```
Downloads /opt/homebrew/bin/code --install-extension vscoq-0.3.9.vsix
Installing extensions...
O [Error]: EISDIR: illegal operation on a directory, read
    at d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:49:4166)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:49:5519
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/yauzl/index.js:37:7
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/yauzl/index.js:110:21
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/yauzl/index.js:627:21
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:684:5) {
  type: undefined,
  cause: [Error: EISDIR: illegal operation on a directory, read] {
    errno: -21,
    code: 'EISDIR',
    syscall: 'read'
  }
}
Failed Installing Extensions: file:///Users/ac132/Downloads/vscoq-0.3.9.vsix
```

**Comment by fasapa** [comment]
It also worked for me!

**Comment by clayrat** [comment]
Switching to `vscoq-0.3.9.vsix` works for me too.

**Comment by HaoYang670** [comment]
It works for me. Thank you very much @thery !!
