### ISSUE TITLE
[VsCoq 1] End section color bug

### ISSUE THREAD

**Issue by dlesbre** [coq-community/vscoq#443]
This is new in vscoq 0.3.8, the `End Foo` command is now always colored as an error:

![image](https://user-images.githubusercontent.com/53176929/224727377-921f545a-ae52-4d40-bb5a-63289370e17c.png)

I think this is due to some code to highlight `end` in red when no `match` is found, as adding an incomplete `match` statement fixes this:

![image](https://user-images.githubusercontent.com/53176929/224728535-202c712a-3064-4f73-bf13-123a6f5342f6.png)

**Comment by 4ever2** [comment]
This doesn't seem to be related to vscoq 0.3.8. 
I get the same result when installing older versions. However, I also didn't notice this problem until recently, so it could maybe be caused by a VS Code update.

**Comment by 4ever2** [comment]
Can confirm that syntax highlighting works with vscoq 0.3.8 and VS Code 1.75.1, but not with VS Code 1.76

**Comment by dlesbre** [comment]
Hmm, it might then have something to do with https://code.visualstudio.com/updates/v1_76#_independent-bracket-pairs-for-matching-and-colorization

**Comment by dlesbre** [comment]
Can confirm that removing the "match" "end" in https://github.com/coq-community/vscoq/blob/vscoq1/client/coq.configuration.json#L50 fixes the issue. For some reason VS Code matches them case-insensitively.
