### ISSUE TITLE
[VSCoq2] Invalidation is incorrect and yields to a inconsistent state

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [coq-community/vscoq#452]
Deleting currently leads to the backend not diffing currently and thereby the state of the proof being incorrect.
By deleting `exfalso` in the following proofs, either by "cutting" the line or deleting it character by character, errors should appear at `H` in the following line. But they do not appear until you reload. 
```coq
Theorem proving_by_false : forall n m : nat, False -> n + m = m + n.
Proof.
    intros. 
    exfalso.
    apply H.
Qed.
```
I am currently working on fixing this issue on the branch `pr/hjda/fix-line-deletion`

**Comment by Hjaltesorgenfrei** [comment]
I think the problem is that we never delete any sentences and just accumulate more over time. 
Applying text edits should remove all the effected sentences. And maybe also the next one, as the dot ending the sentence might be gone? 
We could then see that the sentence is gone and we need to revalidate that part.

**Comment by gares** [comment]
I'm improving the test suite in the pr about proof using. imo this bug could be pin pointed by a test, before we attempt any fix. I'll try to separate the test suite improvements so that we can add a test for the documentManager/document components sooner. without the improvements testing it may be too painful

**Comment by Hjaltesorgenfrei** [comment]
I think part of the problem is in `apply_text_edit` 
```ocaml
let apply_text_edit document edit =
  let loc = RawDoc.loc_of_position document.raw_doc (fst edit).Range.end_ in
  let raw_doc, offset = RawDoc.apply_text_edit document.raw_doc edit in
  log @@ "Edit offset " ^ string_of_int offset;
  let parsed_doc = ParsedDoc.shift_sentences document.parsed_doc loc offset in
```
This also shifts the end of the sentences which are being deleted also. Which means that `stop < start` becomes possible.

**Comment by rtetley** [comment]
This seems to be fixed.
