### ISSUE TITLE
[VsCoq 2] Slow parsing of files

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [coq-community/vscoq#454]
As @Duckapple noted on zulip, parsing is currently very slow on large files. 
Testing it on Stdpp's List.v it takes 6 minutes to reach line 1711 on my machine, https://gitlab.mpi-sws.org/iris/stdpp/-/blob/master/stdpp/list.v#L1711
But if I delete everything after line 1725 and thereby make the file shorter it only takes 2 minutes to parse to the same point in the file. 
So there is probably some growth in parsing time of each sentence with regards to the total length of the file.

My theory is that `send_highlights` is the problem as it sends the highlight state for everything when something changes and not only for the changed part.

**Comment by Hjaltesorgenfrei** [comment]
I can confirm that `send_highlights` is the problem and I am working on a fix for it.

**Comment by maximedenes** [comment]
I guess we could at least squash contiguous regions, so as to reduce the volume of data exchange needed.

**Comment by maximedenes** [comment]
The situation was improved since the report, but it would be good to test again on very large files.

**Comment by Blaisorblade** [comment]
https://github.com/coq-community/vscoq/issues/657 suggests problems remain and might be a duplicate.

**Comment by rtetley** [comment]
I believe this has been solved (see duplicate issue above).
