### ISSUE TITLE
[VsCoq2] Context not correct for given location

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [coq-community/vscoq#458]
`ExecutionManager.get_context` currently uses `Global.env ()` which means that auto completion suggests invalid lemmas which are defined later in the file. 

Example: 
```coq
Theorem proving_by_false : forall n m : nat, False -> n + m = m + n.
Proof.
    apply provin (* Using auto suggest here will suggest the lemma below. *)
Qed.


Theorem proving_by_false_again : forall n m : nat, False -> n + m = m + n.
Proof.
    intros. 
    exfalso.
    apply H.
Qed.
```

It is also not obvious how to fix this as the only other place i could see getting `Env` from is proofview, but that also uses the global context.

**Comment by maximedenes** [comment]
I don't fully understand the problem described here: `ExecutionManager.get_context` indeed uses `Global.env ()`, but only after unfreeze the interp state at that point in the document (https://github.com/coq-community/vscoq/blob/ed40eda53d69dd17c14dce1542c83ddc81cab3e9/language-server/dm/executionManager.ml#L567).
