### ISSUE TITLE
Syntax Highlighting for MLG Files

### ISSUE THREAD

**Issue by alpaylan** [coq-community/vscoq#461]
As far as I understand, there is no support for `.mlg` files in vscoq yet. Are there any plans for this? Otherwise, I can also add a PR if you could point me in the correct direction.

**Comment by ejgallego** [comment]
Merhaba @alpaylan , `.mlg` files are much more close to OCaml files than to Coq files, so what I have done with my Emacs editor is to actually instrument the Tuareg mode for OCaml to recognize them.

Do you have an OCaml development setup ready in VSCode? If so you could try to set the files as OCaml, and see how well this works for you.

I think there is not easy way to have any kind of checking on .mlg files, unless someone introduces `.mlx` files that use PPX so the standard OCaml + ocaml-lsp toolchain can be used.

**Comment by alpaylan** [comment]
OCaml works well enough! Thanks for the advice.
