### ISSUE TITLE
Coqidetop not found

### ISSUE THREAD

**Issue by rongcuid** [coq-community/vscoq#462]
I am using Mac Homebrew installing coq without coqide. It worked before an update, but now vscoq says it cannot find coqidetop. I do not know the details, but does vscoq really require coqide to run?

**Comment by ejgallego** [comment]
@rongcuid , what Coq version are you using?

In 8.17, coqidetop is in the coqide-server package, not sure what homebrew is doing.

But indeed, coqidetop is required for vscoq to run.

**Comment by Blaisorblade** [comment]
Yep, upstream homebrew bug https://github.com/Homebrew/homebrew-core/blob/9c93968d9ef5ea7f0840412c72b78ab8328575f3/Formula/coq.rb#L40 - adding coqide-server should be enough.

**Comment by rongcuid** [comment]
Ah, yes, I upgraded to 8.17.

**Comment by p-linnane** [comment]
> Yep, upstream homebrew bug https://github.com/Homebrew/homebrew-core/blob/9c93968d9ef5ea7f0840412c72b78ab8328575f3/Formula/coq.rb#L40 - adding coqide-server should be enough.

Thanks, I've added this in https://github.com/Homebrew/homebrew-core/pull/128743.

**Comment by rongcuid** [comment]
Looks like it's fixed

**Comment by Blaisorblade** [comment]
Should be; closing for now but let us know.
