### ISSUE TITLE
Inconsistency with coqide in proof within proof using 'assert'.

### ISSUE THREAD

**Issue by absly** [coq-community/vscoq#463]
This is a example shown in 'Software Foundations: Logical Foundations' :
![image](https://user-images.githubusercontent.com/60955486/234177736-aad98ad4-139b-4f4c-97e6-4e84ab986e1f.png)
Theorem plus_rearrange : forall n m p q : nat,
    (n + m) + (p + q) = (m + n) + (p + q).
  Proof.
    intros n m p q.
    assert (H: m + n = n + m).
    { rewrite -> plus_comm. reflexivity. }
    rewrite -> H. 
    reflexivity. 
    Qed.

It works in coqide, but when I use vscoq in vscode and try to interpret it,
an error will occur when interpret 'rewrite -> H. ' like:
Error: Found no subterm matching "m + n" in the current goal.

**Comment by Blaisorblade** [comment]
You're most likely using different Coq versions in CoqIDE and VsCoq.
- it's very hard for IDEs to make a difference on such errors
- I confirmed VsCoq can step through this code, at least with Coq 8.16 and Coq 8.17. But I had to add `Require Import Arith.` for `plus_comm` to work.

You can tell VsCoq to use a different Coq binary via the setting pane — set the `Coqtop: Bin Path` to the folder containing the right `coqc` binary — say the one that coqide is using
![image](https://user-images.githubusercontent.com/289960/234617820-8ee4346a-448d-4f7b-bec2-4cd9e691d020.png)

finding that binary requires more info on your install — this conversation might be best continued on https://coq.zulipchat.com/ in the "Coq users" section.

**Comment by thery** [comment]
Alternatively you can see which version `vscoq` is using by looking at the trace of `Coq Language Server` in the `Output` window (that is available through the `View` Tab. In my case, you can see that it is 8.17
![window](https://user-images.githubusercontent.com/6795190/234622865-2a61c13c-1780-4265-bd70-edc5166f560a.png)
)

**Comment by rtetley** [comment]
Closing as this seems solved.
