### ISSUE TITLE
VSCoq proof-diff seems not to be working  

### ISSUE THREAD

**Issue by shrsv** [coq-community/vscoq#525]
Hello,

First, thanks for making VSCoq. It is helping me work through the Software Foundations course, and learn more about mathematics proofs, and proof assistants.

As a beginner, it is helpful to me to see the progression/flow a proof, and I was recently told that one could use the diff-view for this purpose.

So, I tried this in CoqIDE, and works as expected (can see removed goals in red):

![Selection_1270](https://github.com/coq-community/vscoq/assets/796107/c6a8ad71-83a4-4f53-8d67-173e58266d04)

However, for the same piece of Coq code, I do not see a corresponding diff in VSCoq:

![Selection_1268](https://github.com/coq-community/vscoq/assets/796107/e2fdbf8c-1365-4863-b98d-f61b654a9737)

Note that I have enabled all the diff options in VSCode settings page, and have restarted VSCode already:

![Selection_1269](https://github.com/coq-community/vscoq/assets/796107/fc5d187c-3768-41fb-9965-3ae3340d82cf)

Will be grateful for any help in resolving this. The diff-view seems like a really handy feature to have, especially for a beginner.

Thank you :)

**Comment by huynhtrankhanh** [comment]
On Zulip:
> In VSCode, it's probably somewhere in the VSCoq settings. IIRC, VSCoq largely ignores the vernacular commands for changing IDE settings.

This is true, but I'd like to clarify that in this particular case, you need to run a vernacular command to turn on diffs. The command is `Set Diffs "on".`. VsCoq does process this setting.

**Comment by shrsv** [comment]
@huynhtrankhanh Tried that (unless I'm doing something else wrong)

![image](https://github.com/coq-community/vscoq/assets/796107/05f0ccfe-d4f3-4c4c-ab70-3a4ae12f1a1f)

Still the output is not equivalent to what I find in CoqIDE (ref: screenshot above)

**Comment by 4ever2** [comment]
> This is true, but I'd like to clarify that in this particular case, you need to run a vernacular command to turn on diffs.

Running `Set Diffs "on"` is not necessary if you have enabled diffs in the VsCoq1 settings.


> Still the output is not equivalent to what I find in CoqIDE (ref: screenshot in thread intro)

VsCoq1 and CoqIDE uses two different diff algorithms, so you shouldn't expect the output to always be identical. In particular the diff algorithm of VsCoq1 doesn't handle diff of removed text as well as CoqIDE does.

**Comment by shrsv** [comment]
@4ever2 Got it, thanks for the clarification, wasn't aware of these subtleties. 

If I may ask, is there any possibility for supporting CoqIDE-level diff in VSCode?

**Comment by 4ever2** [comment]
Yes, supporting the CoqIDE diff algorithm in VsCoq is possible. VsCoq1 and CoqIDE uses the same backend and the diff algorithm is implemented in the backend.

However, since VsCoq1 is no longer actively developed it probably won't be integrated.

**Comment by 4ever2** [comment]
@shrsv I had a quick look at what VsCoq does with the diff data passed by the backend. It seems that all the correct classes are passed along to the HTML that VsCoq show in the proof view.
So it might be possible to make the CoqIDE-style diffs work with just a tiny bit of CSS.

**Comment by shrsv** [comment]
Thanks for looking into it, @4ever2 

So, you mean the relevant data is already in the HTML but kept hidden due to css?

**Comment by 4ever2** [comment]
Yes, it is there when diffs are enabled by running `Set Diffs "on"`.

The relevant css classes are
```
start-diff\.added\.bg
end-diff\.added\.bg
start-diff\.added
end-diff\.added
start-diff\.removed\.bg
end-diff\.removed\.bg
start-diff\.removed
end-diff\.removed
```

The HTML looks like 
```html
```

**Comment by shrsv** [comment]
Excellent - I'll try to make a custom build of my own for personal use at least once I get some time. If anyone's interested in merging, I can make a pull request as well.

**Comment by 4ever2** [comment]
@shrsv You can try out this branch https://github.com/4ever2/vscoq/tree/diff-coqidetop 
It gives the same diff as CoqIDE for the goal. Diffs for hypotheses only works partially because the CoqIDE diffs break the code parsing hypotheses. Fixing it shouldn't be hard.

Performance seems to be on par with CoqIDE but I think it can be improved a lot. It is certainly much faster than the old VsCoq diffs.

**Comment by shrsv** [comment]
Thanks @4ever2 for following up and making this work. I'll try it out soon, and let you know how it goes.

**Comment by maximedenes** [comment]
It would be nice to port it to a VsCoq 2 PR, if possible.
