### ISSUE TITLE
Prioritize .v files in explorer?

### ISSUE THREAD

**Issue by JasonGross** [coq-community/vscoq#556]
I'm not sure if this is possible for a vscode extension, but it would be nice to see all the `.v` files at the top of the list below folders, and to have actually meaningful folders come before `.coq-native`.  An option to hide or gray out `.glob`, `.vo`, `.vok`, `.vos`, `.*.aux`, etc, would be nice.  The current look is:
![image](https://github.com/coq-community/vscoq/assets/396076/a917d518-0ec6-44ac-8eb8-5150b7467a35)

**Comment by JasonGross** [comment]
Might be nice to give `.v` files a rooster icon too?
![image](https://github.com/coq-community/vscoq/assets/396076/7788a909-e0cb-46b9-b467-7d5c48dc9dcf)

**Comment by JasonGross** [comment]
But for some reason now I see non-.v files grayed out.  Would still be nice to see them all at the top.
![image](https://github.com/coq-community/vscoq/assets/396076/9093a0fd-7644-4830-98be-2f2f41b08c42)

**Comment by TheoWinterhalter** [comment]
I think this is unrelated to the extension? Files will be greyed out if they are in your gitignore I think.

**Comment by JasonGross** [comment]
I guess it just took a while to load .gitignore then.  I assume file ordering would also be a .gitignore feature if it were to exist at all

Should we leave this open for getting a rooster icon for Coq files?  (Or, insofar as it's desired at all, does that belong in some other extension / file icon theme?)

**Comment by TheoWinterhalter** [comment]
Maybe you can leave it open, in case the extension can actually do some of that, which I don't know.

**Comment by JasonGross** [comment]
And it looks like there's already a rooster icon for Coq files, on new enough versions of the extension?
![image](https://github.com/coq-community/vscoq/assets/396076/2b28ac92-0239-42e3-b652-6d557e4e6c79)
