### ISSUE TITLE
Prepare VsCoq2 to support multiple Coq versions

### ISSUE THREAD

**Issue by Blaisorblade** [coq-community/vscoq#565]
It would be nice if one could use a single VsCoq2 extension with multiple Coq binaries (each with their own `vscoqtop` version).

If the extension<->vscoqtop protocol (or LSP extensions) must evolve, hopefully the VsCoq2 protocol can add enough versioning to enable this later. IIUC, @maximedenes suggests the versioning should be possible.

Zulip Discussion:
https://coq.zulipchat.com/#narrow/stream/237662-VsCoq-devs-.26-users/topic/End_of_file/near/383737932

**Comment by rtetley** [comment]
I believe this is the case since #702
