### ISSUE TITLE
Keyboard shortcut for interpret to point in VsCoq2

### ISSUE THREAD

**Issue by palmskog** [coq-community/vscoq#569]
In VsCoq1, the keyboard shortcut for "interpret to point" is [alt+right](https://github.com/coq-community/vscoq/tree/vscoq1#basic-usage). 

However, this shortcut doesn't work for me in manual mode with vscoq-language-server.1.9.0+coq8.18 and the pre-release Marketplace extension. To preserve the VsCoq1 behavior, how about adding it?

**Comment by rtetley** [comment]
Hi @palmskog, I am having a hard time reproducing the bug. It seems to work fine for me at leas (although I am on Mac). I will check on a different machine. So long can you tell me if it works when you just launch the interpret to point command throught the command palette ? (F1 then start typing intrepret to point it should show up, for reference).

**Comment by palmskog** [comment]
@rtetley OK, it looks like you're right, one of my other extensions was apparently interfering. That is, alt+right actually works when I disable all other extensions.

However, the reason I was trying to use the keyboard shortcut was the the mouse right-click option "Interpret to point" that I always used in VsCoq1 disappeared. Are there any plans to add back the right-click "Interpret to point" via right-click?

**Comment by rtetley** [comment]
That's a good point ! I'll create an issue and add it to the road map ! Thanks !
