### ISSUE TITLE
Obligation status not displayed

### ISSUE THREAD

**Issue by TheoWinterhalter** [coq-community/vscoq#57]
When you use `Program` or `Equations` and you have generated obligations, vscoq doesn't seem to display the obligations anywhere, so you have to guess how many there are left.

**Comment by maximedenes** [comment]
I think this should be fixed on the Coq side. The obligation status is currently emitted as an "info" feedback, and only in verbose mode. If I turn it on from the VsCoq side, I'll get a lot of noise (each definition will produce a "foo is defined" feedback, etc).

**Comment by TheoWinterhalter** [comment]
I see. Shouldn't we get these "info" somewhere though?

**Comment by thery** [comment]
@TheoWinterhalter can we close this issue? I am not sure it is still relevant?

**Comment by TheoWinterhalter** [comment]
It for sure is still relevant with VSCoq 1, but I don't know about VSCoq 2. Do you get notified that you have obligations there?

**Comment by thery** [comment]
@TheoWinterhalter do you have a small example I can test?

**Comment by TheoWinterhalter** [comment]
Sure.
```coq
From Coq Require Import Program.Tactics.

Program Definition foo : nat := _.
```
If you do this, Coq generates one obligation silently.

**Comment by thery** [comment]
Ok the problem persists in Vscoq2 I don't see the Coq message
```
foo has type-checked, generating 1 obligation
Solving obligations automatically...
1 obligation remaining
Obligation 1 of foo: nat.
```                      
anywhere

**Comment by thomas-lamiaux** [comment]
Isn't it solved ? I have this on my computer 
```
From Equations Require Import Equations.

Definition vec A n := { l : list A | length l = n }.

Equations vapp' {A n m} (v1 : vec A n) (v2 : vec A m) : vec A (n + m) :=
vapp' (exist _ ln Hn) (exist _ lm Hm) := exist _ (app ln lm) _.
```

![image](https://github.com/user-attachments/assets/7b2b1ef2-d5ad-4510-92ca-6a81be5b5baa)

**Comment by TheoWinterhalter** [comment]
Ah indeed, I didn't even notice (since I basically started avoiding obligations altogether for this reason). Thanks.
