### ISSUE TITLE
Output spaces instead of non-breaking spaces

### ISSUE THREAD

**Issue by Blaisorblade** [coq-community/vscoq#58]
This is the issue purportedly fixed in https://github.com/siegebell/vscoq/pull/164 (haven't tested the fix in this version).

To test this, try pasting output from any command into a Coq buffer. The parsing errors you get are very hard to debug.
```coq
Lemma plusnO : forall n : nat, n + 0 = n. Admitted.
Check plusnO.
(* Paste the output for a new lemma. *)
Lemma plusnO1 : forall n : nat, n + 0 = n.
(* Error: Syntax error: '.' expected after [vernac:gallina] (in [vernac_aux]). *)
```

Here's a hexdump of the offending line. The non-breaking spaces are visible as (0x)`c2 a0`, while spaces are (0x)`20`.
```
$ echo 'Lemma plusnO1 : forall n : nat, n + 0 = n.'|hexdump -C
00000000  4c 65 6d 6d 61 20 70 6c  75 73 6e 4f 31 20 3a c2  |Lemma plusnO1 :.|
00000010  a0 66 6f 72 61 6c 6c c2  a0 6e c2 a0 3a c2 a0 6e  |.forall..n..:..n|
00000020  61 74 2c c2 a0 6e c2 a0  2b c2 a0 30 c2 a0 3d c2  |at,..n..+..0..=.|
00000030  a0 6e 2e 0a                                       |.n..|
00000034
```

**Comment by maximedenes** [comment]
Could this be due to https://github.com/coq/coq/commit/31ce91dd0a7cf1d780bb7bc1ab4550e0270a4bcd ?

@gares do you know more about this change?

**Comment by maximedenes** [comment]
(more precisely https://github.com/coq/coq/commit/31ce91dd0a7cf1d780bb7bc1ab4550e0270a4bcd#diff-3878b4e91bdfa382a438a509423ad047R25 )

**Comment by Blaisorblade** [comment]
Assuming that's indeed involved: *In XML* that makes sense, you can't write a sequence of spaces (it gets collapsed). Except that spaces in CDATA shouldn't be collapsed (and it's meant for preformatted text, like the pre tag, so it could be appropriate here).
So, the nbsp chars should be turned to spaces after read the text from XML.

**Comment by maximedenes** [comment]
> Using CDATA sections might be easier.

Yes indeed. I investigated this, and came to the following conclusions:
- Coq is indeed turning all whitespace into non-breakable spaces when encoding to XML.
- It seems there was a general confusion in the Coq team between PCDATA and CDATA. Using the latter would have been easier, but the XML library vendored by Coq does not seem to support it.
- On the other side, CoqIDE is turning all non-breakable space into regular spaces. This hints that #59 is probably the right way to go for now, as far as VsCoq is concerned.
- It is still not clear to me why non-breakable spaces breaking the parsing. In particular, I haven't investigated whether it was coming from VsCoq or Coq. It would be funny that while Coq's encoding layer conflates all kinds of whitespace, its parser is not robust w.r.t. the use of non-breakable spaces.
