### ISSUE TITLE
Indentation is imposed

### ISSUE THREAD

**Issue by ybertot** [coq-community/vscoq#603]
Very small example where I start a proof.  After the Proof keyword, my text is indented by 4 characters.  I did not find a way to disable this (at least no way that works).

I am using this version of vscoq :
VsCoq
v1.9.3
Pre-Release

I am using this version of vscode:

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.6-200.fc38.x86_64

Yves

**Comment by TheoWinterhalter** [comment]
Is it using the "Tab Size" preference of the editor?

**Comment by ybertot** [comment]
As a newcomer to this interface, I don't know what is this "Tab Size" preference, or how to change it.

**Comment by 4ever2** [comment]
You can change the tab size preference for a single file in the bottom right corner of the editor.
If you want to change it permanently for all Coq files you can add the following snippet to your VS Code configuration
```
"[coq]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true
},
```

**Comment by TheoWinterhalter** [comment]
You can also use the preference panel and use the search bar to look for "Tab Size".
