### ISSUE TITLE
Problems when installing vscoq-language-server

### ISSUE THREAD

**Issue by slanterns** [coq-community/vscoq#622]
First of all, thank you for the new 2.0 release! The new LSP mode is awesome and makes it remarkably convenient when working with large files. However, I noticed some problems when installing `vscoq-language-server`:

- It cannot be installed by `coq-platform` users that do not have an `opam` (possible solution: bundle it into future `coq-platform`);
- The 2.0 version of the language server is only published on Github release page, not in any opam repo. Even 3rd-party repo https://coq.inria.fr/opam/extra-dev/ has v1.9.3 only, but the extension will complain it requires v2.0.0 (publishing it to https://opam.ocaml.org/ where the package cannot be found will be helpful).

Also, it works with coq-8.18 (or dev versions) only, which was just released one week ago, and most of the users do not have it yet. However, the extension upgrading is done by VSCode automatically, which means users will see the error and need to downgrade the extension manually. It may not be ideal and I wonder if there is a better way to roll out the upgrade.

Thank you again for spending time on this great project!

**Comment by gares** [comment]
See https://github.com/ocaml/opam-repository/pull/24452.

**Comment by rtetley** [comment]
Thanks for your feedback !
Regarding the release, unfortunately the new language server requires some pretty heavy changes in the coq API which were only introduced in 8.18 :-/ 
I agree it is not ideal for users who have yet to upgrade to 8.18 but the only solution we found was to leave VsCoq 2 as a pre-release, which we felt was only viable for beta releases.
And yes for the opam repo, see the pull request linked above ;-)

**Comment by Tghoul-b** [comment]
I can't install opam on windows, who can help me?

**Comment by chandradeepdey** [comment]
Is there a plan to add the opam package into the 8.18 coq-platform release? Maybe as a part of the "IDE level"?

**Comment by gares** [comment]
Yes, tracker https://github.com/coq/platform/issues/347

**Comment by slanterns** [comment]
Great. I believe the remaining things to do is just waiting for the packages to be uploaded.
