### ISSUE TITLE
Version mismatch between vscoq and vscoq-language-server

### ISSUE THREAD

**Issue by EkanshdeepGupta** [coq-community/vscoq#623]
When I install vscoq-language-server from opam, I get `vscoq-language-server 1.9.3+coq8.18`

I installed it using the following commands:
```
$ opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
$ opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
$ opam pin add coq 8.18+rc1
$ opam install vscoq-language-server
```

However, when I install vscoq extension in VSCode, it throws an error saying "This version of VsCoq requires version 2.0.0 of vscoq-language-server"

How can I install version 2.0.0 of vscoq-language-server to satisfy the requirement?

**Comment by EkanshdeepGupta** [comment]
Another comment: it is not clear which opam repos need to be added to install vscoq-language-server. I found these from a random stackoverflow post (https://stackoverflow.com/questions/77106605/vscoq-language-server-failed-installing)

It would be better if the documentation for this repo also listed the correct sequence of commands to install vscoq-language-server instead of just saying "After creating an opam switch, activate these repositories, pin Coq, and install the vscoq-language-server package"

**Comment by chandradeepdey** [comment]
https://github.com/coq-community/vscoq/issues/622

Also, hi lol

**Comment by EkanshdeepGupta** [comment]
So I guess I just wait? Seems like an ill-planned rollout lol.

**Comment by slanterns** [comment]
Despite the error, the extension still works with 1.9.3 :)
