### ISSUE TITLE
Installing instructions very unclear

### ISSUE THREAD

**Issue by waynee95** [coq-community/vscoq#625]
I was trying to install VScoq but I am very much confused by the install instructions. 

It should be noted that I am not an Ocaml user, so these instructions do not tell me much:

> After creating an opam switch, activate  these repositories, pin Coq, and install the vscoq-language-server package

I can somewhat understand what is meant with creating the switch and pinning Coq but what is meant by

"Activating **these** repositories"?

**Comment by slanterns** [comment]
I guess it meant to be https://coq.inria.fr/opam/core-dev and https://coq.inria.fr/opam/extra-dev.

**Comment by rtetley** [comment]
Thanks for replying :-) ! These instructions should be removed as soon as https://github.com/ocaml/opam-repository/pull/24452 is merged ! 
Also please note that if you are using Coq 8.17 or lower, you should downgrade the VsCoq install. Just follow the instructions that have been added to the README: 
https://github.com/coq-community/vscoq#problems-with-vscoq-2
We're busy working through this and making it easier in the future !

**Comment by rtetley** [comment]
This is now solved.
