### ISSUE TITLE
"No package named vscoq-language-server found."

### ISSUE THREAD

**Issue by IronCretin** [coq-community/vscoq#626]
When I attempt to install the language server using the instructions in the readme:

> ### Installing the language server
> 
> After creating an opam switch, activate these repositories, pin Coq,
> and install the `vscoq-language-server` package:
> ```shell
> $ opam install vscoq-language-server
> ```

I recieve the error:
```
[ERROR] No package named vscoq-language-server found.
```

**Comment by slanterns** [comment]
https://github.com/coq-community/vscoq/issues/622
The package is still being submitted.

**Comment by rtetley** [comment]
We had a few issues in releasing the language server. See: https://github.com/ocaml/opam-repository/pull/24452
We're working on fixing it ASAP. 
On another note if you guys are using Coq 8.17 or lower, please refer to the instructions that were added to the README: 
https://github.com/coq-community/vscoq#problems-with-vscoq-2
We're working on a patched release that will link to these in case of problems !
Sorry for the inconvenience ! :-(

**Comment by arnoudvanderleer** [comment]
It has now been merged, so we can proceed!
