### ISSUE TITLE
Auto Scroll on Goal Window

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#636]
On small screen (i.e when the goal window has a scroll bar) would it be possible to automatically scroll to the conclusion of the first goal.

**Comment by thery** [comment]
also when we switch goal, autoscrolling would be nice

**Comment by TheoWinterhalter** [comment]
Another solution would be to split the goal and hypotheses in two separate views no?

**Comment by thery** [comment]
with a small screen I am afraid the hypothesis window would take space. Already the space taken by
`
Main
1
Shelved
0
Given up
is already too big for my taste, fortunately the scrolling will hide this too
`

**Comment by rtetley** [comment]
> also when we switch goal, autoscrolling would be nice

@thery can you clarify what you mean ? Which command in particular would lead to such an autoscroll ?

**Comment by thery** [comment]
everytime the goals are updated. As I said I am on a small screen. Here is an example where I would really like to see some scrolling. The same when I switch goal.
![ddd](https://github.com/coq-community/vscoq/assets/6795190/db67e10c-9f17-48aa-8e33-693279c81623)

**Comment by rtetley** [comment]
I get the auto scroll problem, I am just not sure what you mean with "switch goal" ?

**Comment by rtetley** [comment]
Sorry, had not realized you were talking about the Tab view ;-)
