### ISSUE TITLE
Feature request: showing the next bullet

### ISSUE THREAD

**Issue by toku-sa-n** [coq-community/vscoq#643]
Hi. I'm using VsCoq, and it's pretty nice! However, I think it'd be great if VsCoq prints the next bullet on the completion of proof for a bullet.

Currently, VsCoq only says "No more subgoals".
![29-09-2023_19:09:46_screenshot](https://github.com/coq-community/vscoq/assets/42336339/aeabee67-1d0f-49e3-80b1-8f94a9fa675e)

[Coqtail](https://github.com/whonore/Coqtail), a Vim plugin for Coq, has the feature like this.
![29-09-2023_19:08:19_screenshot](https://github.com/coq-community/vscoq/assets/42336339/b6fd302c-6fb8-40fe-a817-a19bff8caee7)

I'm using VsCoq 2.0.1 and vscoq-language-server 2.0.1+coq8.18.

**Comment by SkySkimmer** [comment]
You probably want something like https://github.com/coq/coq/blob/a37a2e4bf622d7c2a6a0ec9fe9d58d981a142442/printing/printer.ml#L966-L972
The Proof_bullet.suggest says "focus next goal with bullet -"
pr_subgoals on `bgoals = Proof.background_subgoals p` does the actual goal printing

**Comment by gares** [comment]
Thanks @SkySkimmer . If we add a quickfix for that in Coq, there is nothing to do here in VSCoq.

**Comment by SkySkimmer** [comment]
WDYM? Coq already prints this info (with coqtop in proof general)

**Comment by gares** [comment]
I mean generating a proper quickfix as in LSP. Warnings as errors can carry one, maybe plain errors cannot yet.I don't recall the API.

I guess the only sensitive piece of info is the loc, I.e. the piece of text to be replaced by the right bullet. If it is a bad bullet, then it is the loc of the whole bullet. If it is a Missi g bullet, it must be so white space before the tactic.

**Comment by SkySkimmer** [comment]
There is no warning or error involved here.

**Comment by TheoWinterhalter** [comment]
I think it should just replace the text that says "No more goals" which is incorrect and replace it with the one Coq outputs.

**Comment by Durbatuluk1701** [comment]
> Thanks to @SkySkimmer I now detect unfocused goal (see linked PR). However all I do is write a message. Seeing as we already have Shelved and Given Up tabs, would it not make sense to make a Unfocused tab ? Or should I just display the unfocused goals like Coqtail does ?

I would advocate for automatically displaying the unfocused goals (or at the very least making an option to do so). If I have to mouse over to an Unfocused tab to see them I would likely just never do so.

**Comment by rtetley** [comment]
Okay so I came up with this:
<img width="791" alt="Screenshot 2024-09-13 at 11 45 02" src="https://github.com/user-attachments/assets/8e484bb8-1566-40cc-9984-19c18d23e3de">

It displays all the unfocused goals but makes them all collapsed by default. WDYT ?

**Comment by TheoWinterhalter** [comment]
Shouldn't it say "focus with bullet"?

**Comment by rtetley** [comment]
Good catch 😅
