### ISSUE TITLE
Fail output is lost

### ISSUE THREAD

**Issue by gares** [coq-community/vscoq#658]
I think the failure message should be presented, maybe as an info and not an error, but should be visible.

![Screenshot from 2023-10-11 12-58-46](https://github.com/coq-community/vscoq/assets/1013846/8a3add7a-270c-4555-b4a0-cc266c3edb6c)

**Comment by ybertot** [comment]
I needed a solution to this issue again today.

**Comment by TheoWinterhalter** [comment]
I just tested in 2.1.6 and it seems it still prints nothing.
