### ISSUE TITLE
Bug in Pretty Printing

### ISSUE THREAD

**Issue by mukeshtiwari** [coq-community/vscoq#670]
I recently switched to Coq-8.18.0 and VsCoq2.  The following code does not parse very well. 

```
From Coq Require Import NArith Utf8
    Bool Init.Byte Psatz Strings.Byte. 


Open Scope N_scope.
Definition np_total (np : N):  (np <? 256 = true) ->  byte.
Proof.
  intros H.
  refine(match (np <? 256) as b return ∀ mp, np = mp -> 
      (mp <? 256) = b -> _ with 
   | true => fun mp Hmp Hmpt => 
      match of_N mp as npt return _ = npt -> _ with 
      | Some x => fun _ => x
      | None => fun Hf => _  
      end eq_refl
   | false => fun mp Hmp Hmf => _
  end np eq_refl eq_refl).
  abstract(
  apply of_N_None_iff in Hf;
  apply N.ltb_lt in Hmpt; intuition nia).
  abstract (subst; congruence).
Defined.


Lemma np_true_tmp : forall np (Ha : np <? 256 = true) x, 
  of_N np = Some x -> np_total np Ha = x.
Proof.
  intros * Hb; unfold np_total.
  
```

<img width="1728" alt="Screenshot 2023-10-14 at 12 53 48" src="https://github.com/coq-community/vscoq/assets/1135077/9dae3140-0e43-4744-a033-5d6da1d3277a">

**Comment by mukeshtiwari** [comment]
Never mind. I uninstalled all the plugins related to Coq and reinstalled VsCoq2 and it seems to work. Apologies for the noise. I am closing the issue. 

<img width="1728" alt="Screenshot 2023-10-14 at 13 08 02" src="https://github.com/coq-community/vscoq/assets/1135077/b1f46ad8-b17a-4df9-97d0-1955b591cb2f">

**Comment by mukeshtiwari** [comment]
I removed my coq-lsp [1] (I am not sure if I need this or not) and proof-general keybindings. When I am searching for a relevant theorem, the message pane shows a list of theorems that matches the query.

<img width="1728" alt="Screenshot 2023-10-14 at 13 43 37" src="https://github.com/coq-community/vscoq/assets/1135077/da94bf8e-5d6d-493d-b277-0d9199004ff7">

However, if I try to do something which is an error, then message pane shows nothing. Is this an intended behaviour? 
<img width="1728" alt="Screenshot 2023-10-14 at 13 48 56" src="https://github.com/coq-community/vscoq/assets/1135077/c740d5b8-203a-4de6-9087-8801cff183fb">

The only plugins I have installed are VsCoq2.0.1 and Coq Elpi lang v0.0.5. 

[1] https://github.com/ejgallego/coq-lsp

**Comment by maximedenes** [comment]
> I removed my coq-lsp [1]

You don't need coq-lsp for VsCoq to work. They are two independent projects.

> When I am searching for a relevant theorem, the message pane shows a list of theorems that matches the query.

Note that you also have a dedicated query panel (you'll see a Coq icon if you activate the activity bar on the left). It may be more convenient than typing your queries in the Coq document.

> However, if I try to do something which is an error, then message pane shows nothing. Is this an intended behaviour?

No, the errors are indeed expected to show up in the messages pane. Where is your cursor at, in the second screenshot?

**Comment by mukeshtiwari** [comment]
> Note that you also have a dedicated query panel (you'll see a Coq icon if you activate the activity bar on the left). It may be more convenient than typing your queries in the Coq document.

Oh, that is nice!  I will give it another shot, probably next week again.

> No, the errors are indeed expected to show up in the messages pane. Where is your cursor at, in the second screenshot?

The cursor was just before the dot (.) but I tried to move along the command (rewrite Ha) as well, e.g., in the beginning or in the middle but I didn't get anything.

**Comment by mukeshtiwari** [comment]
I tried again and I think there is some bug in displaying the error messages. As you can see from the picture, my cursor is just before the dot (.) but there is no error message in the message pane. 
<img width="1728" alt="Screenshot 2023-10-15 at 19 48 15" src="https://github.com/coq-community/vscoq/assets/1135077/c476f210-1dc4-434b-af09-0777bd4f44ce">

I am using VsCoq v2.0.1 on Apple M1 Pro (macOS Sonoma 14.0)

**Comment by mukeshtiwari** [comment]
Some more issues: same file is opened in Vscode and Emacs. 

<img width="1082" alt="Screenshot 2023-10-15 at 21 27 08" src="https://github.com/coq-community/vscoq/assets/1135077/2ff8783e-67fa-4ae9-b143-2f8b0962f239">


<img width="575" alt="Screenshot 2023-10-15 at 21 29 01" src="https://github.com/coq-community/vscoq/assets/1135077/a865a3f3-2a00-473f-a567-5c8d09e6eebb">

**Comment by rtetley** [comment]
Concerning the errors, could it be that they are disabled in your user settings ? They are actually disabled by default. In settings check that Vscoq > Goals > Messages: Full is ticked. 
Concerning your latest issue it will be solved in the upcoming release (I plan to start the process today), see #664

**Comment by mukeshtiwari** [comment]
> Concerning the errors, could it be that they are disabled in your user settings ? They are actually disabled by default. In settings check that Vscoq > Goals > Messages: Full is ticked. 

Thanks! This worked for me. 

More info on the previous Coq code. I typed the whole things and after some time, it crashed (see the output)
<img width="1728" alt="Screenshot 2023-10-16 at 07 49 08" src="https://github.com/coq-community/vscoq/assets/1135077/fae72fd2-816b-482a-9f03-f59f13be2eae">

Then I restarted and it worked. I don't know what is going on but hopefully, it is helpful for you :) 

<img width="1728" alt="Screenshot 2023-10-16 at 07 50 03" src="https://github.com/coq-community/vscoq/assets/1135077/1aa78eb1-fb10-47a3-9fa9-d1bf3a2727d4">

**Comment by rtetley** [comment]
I think if you use unicode characters it will be very buggy **(until the next release)**. This is because the version you are using does not handle such characters correctly and edits are not passed on correctly to the language server. This should be fixed in the upcoming release (just started the release process). Until then I would recommend against using unicode characters :-) 
Thanks for your feedback anyways ! Can we close this issue ? If you have anything else not relating to pretty printing we can open a new one ! Thanks again !

**Comment by mukeshtiwari** [comment]
Yeah, you can close the issue.

Best,
Mukesh
