### ISSUE TITLE
Goal Position in VsCoq2

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#674]
Now that goals are automatically scrolled (which is great!).  In manual mode it is difficult to figure out quickly if a command has created some subgoals .
Would it be possible to put back the the goal position in the separator between the hypothesis and the conclusion  that was in VsCoq1, this was very handy. Something like 
![ddd](https://github.com/coq-community/vscoq/assets/6795190/9a88dc76-79b6-4ef9-901c-8bfdef94a818)

**Comment by thery** [comment]
@rtetley is it supposed to be in 2.0.3. I don't see it

**Comment by rtetley** [comment]
<img width="644" alt="Screenshot 2023-12-14 at 08 49 35" src="https://github.com/coq-community/vscoq/assets/32383664/3948e873-3a56-4569-abd2-f06fd44a76bb">
I see it, however I think I assumed you would not need it in Tab mode... That might have been s bit of a silly assumption ?

**Comment by thery** [comment]
🕵️ I am in Tab mode ☹️
![ddd](https://github.com/coq-community/vscoq/assets/6795190/468a0470-3b09-4993-92a5-c5023e3288e3)
