### ISSUE TITLE
Getting stuck in manual mode

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#675]
I often end up in a state where vscoq is not reacting .
Unfortunately I cannot make it to get a minimal example.
I've just  the trace set on.

Here I ask to execute `have F : True` and nothing happens

![ddd](https://github.com/coq-community/vscoq/assets/6795190/6f7bc900-b4c0-40f1-913e-bbbc3b9df301)

here is the trace
[trace.txt](https://github.com/coq-community/vscoq/files/13013358/trace.txt)

what is going on?

**Comment by rtetley** [comment]
I believe this was fixed by #727 and is part of the next release (coming this week).
This was due to the language client not correctly re-connecting to the server when the server crashed and restarted.
Re-open if you experience this again after v2.1.1
