### ISSUE TITLE
[notation-overridden,parsing,default] on `all_ssreflect` import

### ISSUE THREAD

**Issue by 0xGeorgii** [coq-community/vscoq#692]
Hi. I just installed `vscoq` extension alongside the LS and `ssreflect` and on the import I see the following errors:

```coq
From mathcomp Require Import all_ssreflect.
```
![image](https://github.com/coq-community/vscoq/assets/22812032/7b48a991-c717-4c95-8dd9-a919a802eeae)

Can you please help solve this problem? I use `Ubuntu23.10`

**Comment by 0xGeorgii** [comment]
Fixed by reducing to
```coq
From mathcomp Require Import ssreflect seq.
```

but what interfered?

**Comment by SkySkimmer** [comment]
These are warnings not errors.

**Comment by 0xGeorgii** [comment]
> These are warnings not errors.

but I suppose they should not be

**Comment by TheoWinterhalter** [comment]
They're warnings of Coq, not of VSCoq. I agree that this is annoying, but this should be a bug for mathcomp I think.

**Comment by rtetley** [comment]
Pinging @gares

**Comment by rtetley** [comment]
Closing as I believe this is unrelated to vscoq itself.
