### ISSUE TITLE
Visual Studio Marketplace release

### ISSUE THREAD

**Issue by liyishuai** [coq-community/vscoq#7]
The current Marketplace [release](https://marketplace.visualstudio.com/items?itemName=siegebell.vscoq) tracks the original [repo](https://github.com/siegebell/vscoq). We might need to switch its upstream to here, or create another Marketplace entry.

**Comment by maximedenes** [comment]
Yes, I plan to do so once I push a few more fixes. There are still things that don't work well with recent Coq versions.

**Comment by varosi** [comment]
How could I may install coq-community version?

**Comment by varosi** [comment]
Thanks!

**Comment by varosi** [comment]
On **make compile** I got:

> cd server && npm compile
> 
> Usage: npm <command>
> 
> where <command> is one of:
>     access, adduser, audit, bin, bugs, c, cache, ci, cit,
>     clean-install, clean-install-test, completion, config,
>     create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
>     edit, explore, get, help, help-search, hook, i, init,
>     install, install-ci-test, install-test, it, link, list, ln,
>     login, logout, ls, org, outdated, owner, pack, ping, prefix,
>     profile, prune, publish, rb, rebuild, repo, restart, root,
>     run, run-script, s, se, search, set, shrinkwrap, star,
>     stars, start, stop, t, team, test, token, tst, un,
>     uninstall, unpublish, unstar, up, update, v, version, view,
>     whoami
> 
> npm <command> -h  quick help on <command>
> npm -l            display full usage info
> npm help <term>   search for help on <term>
> npm help npm      involved overview

My Node on Mac is v12.9.1

**Comment by varosi** [comment]
Next and last command in the documentation is make vsix, which do:

> rm -rf html_views/node_modules server/node_modules client/node_modules
> rm -rf client/server client/html_views
> cd html_views && npm install
> 
> > fsevents@1.2.9 install /Users/vasko/Projects/github/vscoq/html_views/node_modules/fsevents
> > node install
> 
> node-pre-gyp WARN Using needle for node-pre-gyp https download 
> [fsevents] Success: "/Users/vasko/Projects/github/vscoq/html_views/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote
> 
> > vscoq-html-views@0.0.1 postinstall /Users/vasko/Projects/github/vscoq/html_views
> > typings install
> 
> typings WARN deprecated 9/29/2016: "registry:dt/jquery#1.10.0+20160704162008" is deprecated (updated, replaced or removed)
> 
> └── jquery (global)
> 
> added 599 packages from 326 contributors and audited 3124 packages in 6.761s
> found 13 vulnerabilities (4 low, 9 high)
>   run `npm audit fix` to fix them, or `npm audit` for details
> cd server && npm install
> npm WARN coqlangserver@0.0.1 license should be a valid SPDX license expression
> 
> added 53 packages from 391 contributors and audited 58 packages in 0.915s
> found 2 vulnerabilities (1 low, 1 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details
> cd client && npm install
> 
> > vscoq@0.2.7 postinstall /Users/vasko/Projects/github/vscoq/client
> > node ./node_modules/vscode/bin/install
> 
> Detected VS Code engine version: ^1.7.0
> Found minimal version that qualifies engine range: 1.7.1
> Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/vscode.d.ts
> vscode.d.ts successfully installed!
> 
> added 124 packages from 629 contributors and audited 206 packages in 3.966s
> found 1 high severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details
> cd client && vsce package
> Executing prepublish script 'npm run vscode:prepublish'...
>  ERROR  Command failed: npm run vscode:prepublish
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN coqlangserver@0.0.1 license should be a valid SPDX license expression
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! coqlangserver@0.0.1 compile: `installServerIntoExtension ../client ./package.json ./tsconfig.json && tsc -p ./`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the coqlangserver@0.0.1 compile script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/vasko/.npm/_logs/2019-08-28T16_09_32_286Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! vscoq@0.2.7 compile-server: `cd ../server && npm run compile && cd ../client`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the vscoq@0.2.7 compile-server script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/vasko/.npm/_logs/2019-08-28T16_09_32_304Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! vscoq@0.2.7 vscode:prepublish: `npm run cp-coqtopw && npm run compile-server && npm run compile-html-view && npm run compile`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the vscoq@0.2.7 vscode:prepublish script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/vasko/.npm/_logs/2019-08-28T16_09_32_320Z-debug.log
> 
> make: *** [vsix] Error 1

**Comment by varosi** [comment]
Error from the log file:

> 9 verbose lifecycle coqlangserver@0.0.1 compile: CWD: /Users/vasko/Projects/github/vscoq/server
> 10 silly lifecycle coqlangserver@0.0.1 compile: Args: [
> 10 silly lifecycle   '-c',
> 10 silly lifecycle   'installServerIntoExtension ../client ./package.json ./tsconfig.json && tsc -p ./'
> 10 silly lifecycle ]
> 11 silly lifecycle coqlangserver@0.0.1~compile: Returned: code: 2  signal: null

**Comment by maximedenes** [comment]
I would suggest to wait until we prepare a marketplace release.

**Comment by varosi** [comment]
Okay, thanks!

**Comment by maximedenes** [comment]
First release here: https://marketplace.visualstudio.com/items?itemName=maximedenes.vscoq

I'm expecting some issues, so feedback is particularly welcome.

**Comment by Zimmi48** [comment]
In the end, did it turn out to be too complicated to release under an organization name, or is this because you are not doing this until you get feedback?

**Comment by maximedenes** [comment]
I did release under the organization "coq-community" that I created on Azure Devops.

**Comment by Zimmi48** [comment]
I don't get it. Why is the package called maximedenes.vscoq and not coq-community.vscoq then?

**Comment by maximedenes** [comment]
Because that's the publisher, not the organization.

**Comment by Zimmi48** [comment]
BTW, the README should be changed now that this has been released.

**Comment by brendanzab** [comment]
Seems like the Rust extension has its own publisher: https://marketplace.visualstudio.com/items?itemName=rust-lang.rust - I was also surprised that it was under one person's name when I looked for the new version! 😅

**Comment by Zimmi48** [comment]
> BTW, the README should be changed now that this has been released.

Should I open a new issue about this?
