### ISSUE TITLE
vscoq2 gets stuck after intros.

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#700]
I am in manual mode
![ddd](https://github.com/coq-community/vscoq/assets/6795190/3fb0c11c-361c-4a86-9ef0-d7a92dfd0e79)

after executing step by step this example [gauss_int.v](https://github.com/coq-community/vscoq/files/13683760/gauss_int.v.txt), I get stuck after the first intros

**Comment by thery** [comment]
minimize the [example](https://github.com/coq-community/vscoq/files/13702410/foo.v.txt)

**Comment by rtetley** [comment]
I'm unable to reproduce with VsCoq 2.0.3

**Comment by rtetley** [comment]
@thery tried to reproduce with both files, it works on my set-up. Could it be linked to some other issue ?

**Comment by thery** [comment]
It works too in my setting now. My bad I should have put in the message my exact config (coq + language server+ vscoq)

**Comment by rtetley** [comment]
I will close for now. Feel free to re-open if it happens again !
