### ISSUE TITLE
Output recorded in reverse order

### ISSUE THREAD

**Issue by gares** [coq-community/vscoq#705]
![Screenshot from 2024-01-04 14-43-50](https://github.com/coq-community/vscoq/assets/1013846/f4fa9c8d-d8e8-4d6b-9d96-07e5dd537569)

The command in question prints (emits feedback) multiple times (one per line).
The feedback is presented in reverse order.

**Comment by rtetley** [comment]
@gares I think this was closed by #874. Would you mind checking and closing ?
