### ISSUE TITLE
Navigation bug with plugin loading

### ISSUE THREAD

**Issue by rtetley** [coq-community/vscoq#707]
The following example creates a weird bug. To reproduce step forward and backward on top of the document. This will issue a warning. 

```
Require Import Extraction.
Module plus.
End plus.
Extraction plus.
```

Warning: 
```
A Coq plugin was loaded inside a local scope (such as a Section). It is recommended to load plugins at the start of the file. Summary entry: Extraction Output Directory-SUMMARY [summary-out-of-scope]
```

**Comment by gares** [comment]
Ocaml cannot unload plugin code. I guess this is where the problem begins...

**Comment by rtetley** [comment]
Unable to reproduce on master. Closing.
