### ISSUE TITLE
Forward/backward shortcut in continuous mode

### ISSUE THREAD

**Issue by damhiya** [coq-community/vscoq#712]
It appears that the continuous mode disables the step forward/backward shortcut. I believe these key bindings are quite useful even in continuous mode. Could we enable such shortcuts in continuous mode?

**Comment by rtetley** [comment]
Practically how would this work ? In manual mode, the step forward/backward is done with respect to a current internal state. In continuous mode do you mean you would then step forward/backward with respect to the current cursor position ? Just to clarify !

**Comment by damhiya** [comment]
> Practically how would this work ? In manual mode, the step forward/backward is done with respect to a current internal state. In continuous mode do you mean you would then step forward/backward with respect to the current cursor position ? Just to clarify !

Yes! I guess step forward/backward with respect to the current cursor position is appropriate.
