### ISSUE TITLE
Closed Files Still Use Memory

### ISSUE THREAD

**Issue by joscoh** [coq-community/vscoq#751]
As mentioned on Zulip, when a file is closed in VSCoq2, the memory is still in use. (I am using VSCoq version 2.1.2) This means that after opening and interactively editing several files, `vscoqtop` uses huge amounts of memory (>6 GB for 2 files), and there is no way to reduce the memory usage except by closing the VSCode window. In VSCoq legacy, closing a file freed the memory associated with that file's Coq buffer.

**Comment by rtetley** [comment]
Hey @joscoh ! I agree this is a problem. I am working on a fix which would discard the document state / edits when you close a file but that would of course mean re-opening it will require re-executing it (the execution state is probably what is taking up most of the memory). Would that be an acceptable policy ? What do you think @gares ?
