### ISSUE TITLE
Bad alignment in the output of "Print Universes Subgraph"

### ISSUE THREAD

**Issue by YaZko** [coq-community/vscoq#752]
A minor QoL nitpick, but in the following code:

```coq
Universe u v.
Print Universes Subgraph (u v).
```

Vscoq displays:

```
Set < u
< v
```
while proof general displays the easier to parse aligned version:
```
Set < u
    < v
```

**Comment by rtetley** [comment]
This is still not solved with the new pretty printing library, and is related to #835
