### ISSUE TITLE
Error handling if coq fails to start could be more robust

### ISSUE THREAD

**Issue by Blaisorblade** [coq-community/vscoq#77]
If Coq fails to start, that could be shown more clearly than it is right now. Not high-priority of course, but it'd be nice at some point.

To reproduce, it's enough add `"coqtop.args": ["a"],` to `settings.json`, and try to "Interpret to point." till some point in a document.

Code gets highlighted till that point, but the error doesn't seem to be handled properly. the command never seems to complete properly and dehighlight the source, and the GUI enters an inconsistent state.

I also have a [VsCodeVim](https://github.com/VSCodeVim/Vim/) binding for "interpret to point" — since the command does not "complete" the right way, the whole vim layer crashes. The same happens when trying to cancel a long-running command, BTW.

One can try "Interpret to point" again, but the state stays inconsistent.

"Coq: Reset" still works, but after a few times, you get one or both of "Connection to server got closed. Server will not be restarted." and an visual error saying that coq crashed too often, and then even "Coq: Reset" doesn't work (and causes a "Language client is not ready yet" error to appear).

Backtrace:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Full log at https://gist.github.com/Blaisorblade/71eefaef3c8bbaf27c7970946b9dbb25.

**Comment by Blaisorblade** [comment]
To be clear, adding invalid arguments isn't a good use case — but "something is wrong with Coq, please tell me" is. (I had just upgraded vscoq and forgot my change, so it wasn't obvious).

Also, what's `coqtop-stderr`? That threw me off. In retrospect, that's output from coqtop's stderr, but it's hidden among internal output that you learn to never look at...

**Comment by maximedenes** [comment]
Yep, I've noticed too that such errors are not well reported. #52 is related.
