### ISSUE TITLE
coqtop could not be started: Error: spawn coqidetop.opt ENOENT

### ISSUE THREAD

**Issue by iamlazynic** [coq-community/vscoq#78]
### Problem

`coqtop could not be started: Error: spawn coqidetop.opt ENOENT`

This error appears after I opened a `.v` file with vscode, and tried to use "Step forward" or any other similar function. The output in Coq Language Server log:

```
Listening at 127.0.0.1:62923
Listening at 127.0.0.1:62924
Listening at 127.0.0.1:62925
Listening at 127.0.0.1:62926
starting coqtop
exec: coqtop -v
Listening at 127.0.0.1:62933
Listening at 127.0.0.1:62934
Listening at 127.0.0.1:62935
Listening at 127.0.0.1:62936
Detected coqtop version 8.10.0
Coqtop version parsed into semver version 8.10.0
exec: coqidetop.opt -main-channel 127.0.0.1:62935:62933 -control-channel 127.0.0.1:62936:62934 -async-proofs on -topfile file:///c%3A/Users/nickl/Documents/Workspace/lf/Lists.v
coqtop started with pid undefined
coqtop could not be started: Error: spawn coqidetop.opt ENOENT
onCoqClosed(coqtop closed with code: Error: spawn coqidetop.opt ENOENT)
onCoqClosed(undefined)
coqtop closed with code: -4058
Listening at 127.0.0.1:62937
Listening at 127.0.0.1:62938
Listening at 127.0.0.1:62939
Listening at 127.0.0.1:62940
```

"Coq: Reset" doesn't help.

### Environment

Windows 10. Installed Coq with scoop. CoqIde works flawlessly.

```
> coqtop --version
The Coq Proof Assistant, version 8.10.0 (October 2019)
compiled on Oct 7 2019 17:28:53 with OCaml 4.07.1

> code --version
1.39.2
6ab598523be7a800d7f3eb4d92d7ab9a66069390
x64
```

VSCoq extension version: 0.3.0

**Comment by maximedenes** [comment]
Hello,

Is there a `coqidetop.top` in the same directory as `coqtop`?

**Comment by maximedenes** [comment]
(sorry, I edited the name of the file)

**Comment by maximedenes** [comment]
@iamlazynic did you manage to identify the source of the problem?

**Comment by iamlazynic** [comment]
> Hello,
> 
> Is there a `coqidetop.opt` in the same directory as `coqtop`?

Yes. The actual files of `coqtop.exe` and `coqtop.opt.exe` exist in the same directory. There is only _shim_ for `coqtop.exe` though, which I believe was created by scoop. I don't know whether that's the problem.

Sorry for the delay.

**Comment by iamlazynic** [comment]
Well, it is the problem. `coqtop.opt.exe` wasn't in path.

I added it to path and this extension works now. Thanks!

**Comment by brando90** [comment]
how is this related to https://github.com/coq-community/vscoq/issues/243 issue?
