### ISSUE TITLE
vscoq 2.1.3, break seems broken

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#803]
Here is my example
```coq
Goal forall A B C D E F : Prop, A -> B -> C -> D -> E -> F -> A.
Proof.
intros A B C D E F.
intros HA; intros HB; intros HC; intros HD; intros HE; intros HF; exact HA.
Qed.
```
if I execute everything
![ddd1](https://github.com/coq-community/vscoq/assets/6795190/94e7e955-bd77-4ad7-8161-07a764f00739)
if I try to break the line after `HE;`
The interface goes into an inconsistent state
![ddd2](https://github.com/coq-community/vscoq/assets/6795190/1b5f0d4c-210c-4784-a5ff-9a8e6782aa74)

**Comment by gares** [comment]
I think the range stuff was not invalidated since the document is not.
The code did detect that the texts parses to the same token list, so no need to recompute.
But since the new text is different in length/number-of-lines, the highlighting state needs to be invalidated hence recomputed.

**Comment by gares** [comment]
The colors did not move at all, this is why I'm giving this analysis of the bug.
