### ISSUE TITLE
Bad interaction Vscoq2.1.3 Ltac2

### ISSUE THREAD

**Issue by ybertot** [coq-community/vscoq#813]
The following minimized example raises an anomaly, while the code is correct (as verifiable with coqc or coqtop).

When removing the `Ltac2` import line the anomaly disappears.
```
Require Import List Reals.
From Ltac2 Require Import Ltac2.

Open Scope R_scope.
Lemma toto : True.
Proof.
assert (H : nth 0 (nat_rect (fun _ => list R)
           (0 :: 1 :: nil)
         (fun _ l => (nth 1 l 0 ::
                nth 0 l 0 + nth 1 l 0 :: nil)) 0) 0 = 0).
```

**Comment by SkySkimmer** [comment]
This is probably a coq bug fixed in 8.19.2 https://github.com/coq/coq/pull/19096
also duplicate https://github.com/coq-community/vscoq/issues/772

**Comment by kciray8** [comment]
Is it safe to use vscoq with 8.19.2 ? It is specified to use 8.18.0 in the instruction, I thought they haven't updated it yet

**Comment by kciray8** [comment]
Indeed, when I updated to 8.19.2, problem solved. Thanks!

**Comment by rtetley** [comment]
The documentation is a little ambiguous... You are not the first to assume that we only support 8.18.0 when in fact we currently support any version >= 8.18.0
I will make it clearer !

And thanks for the reporting :-)
