### ISSUE TITLE
Notice messages not shown ?

### ISSUE THREAD

**Issue by FissoreD** [coq-community/vscoq#815]
I am executing the following code snippet,
```coq
Class A.
Instance a : A := {}.

Set Typeclasses Debug.
Goal A. apply _. Qed.
```
However, I cannot see the trace of typeclass search. 

Expected output:
```
Calling typeclass resolution with flags: depth = ∞,unique = false,fail = true
1: looking for A without backtracking
1.1: exact a on A, 0 subgoal(s)
```

Am I missing something ?

I did the same test in VSCoq legacy and the log is displayed

**Comment by rtetley** [comment]
Closed by #842
