### ISSUE TITLE
Debug messages should be displayed somewhere

### ISSUE THREAD

**Issue by gares** [coq-community/vscoq#820]
Apparently they are not visible. I can't tell if they are not visible only when an error occurs, but at least in that case they are not.

Here what the legacy server displays:
![Screenshot from 2024-07-04 10-16-04](https://github.com/coq-community/vscoq/assets/1013846/33507303-cf75-4740-be7e-98daba9326d8)

**Comment by rtetley** [comment]
Closed by #842
