### ISSUE TITLE
Unsatisfactory line break

### ISSUE THREAD

**Issue by ybertot** [coq-community/vscoq#835]
In the attached picture the formatting of the last n - 2 is weird.
![Screenshot at 2024-07-18 14-12-24](https://github.com/user-attachments/assets/5b8bbad7-ab4d-45eb-9a64-c327b48f12bf)

**Comment by tomtomjhj** [comment]
It seems vscoq doesn't take account of notation formatting yet. 

For example, this is what I get from a big term with Iris notations in Coqtail (using coqidetop) and vscoq2.

Notation definition:
```coq
Reserved Notation "P ∗ Q" (at level 80, right associativity, format "P  ∗  '/' Q").
```
(https://gitlab.mpi-sws.org/iris/iris/-/blob/8a98d00a6ddc25ab6918ee8d216558eaf46b6d53/iris/bi/notation.v#L37)

* Coqtail: 
  <img src="https://github.com/user-attachments/assets/7957fa70-0e5d-4c8f-a835-821cddd015a4" width="500">
* vscoq 2.1.7: ![image](https://github.com/user-attachments/assets/88217f74-a0b6-4b47-b84e-6f49552f03bf)

I wonder the vscoqtop server can utilize the coqidetop's logic for formatting, which I believe is used here: https://github.com/coq/coq/blob/d6550d16f01d39dee97f7e645e415de51725fd2e/ide/coqide/idetop.ml#L141. If the server implements this functionality, then the client doesn't need to do the complex stuff. (For the context, I'm the author of neovim client for vscoqtop. https://github.com/tomtomjhj/vscoq.nvim)

**Comment by TheoWinterhalter** [comment]
Related to #859, in particular the discussion which suggests not to reuse `coidetop`'s formatting.

**Comment by tomtomjhj** [comment]
Oh so the response from vscoqtop does contain the formatting information for notations, but the client isn't fully utilizing that yet.
