### ISSUE TITLE
Change keybindings

### ISSUE THREAD

**Issue by vsiles** [coq-community/vscoq#85]
Hi,
I looked around but I didn't find a way to override the default keybinding to use my own flavor. (Since I'm new to vscode, I probably just missed it).
Is it possible to update the keybinding and how to do it ?

Best,
Vincent

**Comment by gares** [comment]
Look here:
  https://code.visualstudio.com/docs/getstarted/keybindings
IIRC there is "coq" in the name of the bindings you want to change.

**Comment by vsiles** [comment]
Just what I needed, thanks a lot
