### ISSUE TITLE
Significant delay between tactic completion and goal space update

### ISSUE THREAD

**Issue by CharlesAverill** [coq-community/vscoq#869]
I just upgraded from VSCoq 0.3.9 to 2.1.7, and I've noticed a significant delay (~1 second) between the completion of some tactics and the re-render of the goal space in the goal window. I'm on Coq .19.0, NixOS, coq and the language server installed via opam.

**Comment by TheoWinterhalter** [comment]
Is this perhaps related to #859?

**Comment by CharlesAverill** [comment]
Possibly, but on 0.3.9 the same goals render instantly. Are the newer versions known to have performance issues?

**Comment by TheoWinterhalter** [comment]
That's basically what the discussion in #859 is about I think.

**Comment by rtetley** [comment]
Yes currently, compared to VsCoq Legacy we format the goal in the front end, instead of asking for a pre-formatted version directly sent by Coq. There are currently performance issues when goals get large. This might be why it happens in some tactics for you !

**Comment by rtetley** [comment]
I'll keep this even though we have #859 as I would say this is more about improving the performance of rendering goals
