### ISSUE TITLE
Add a button to open and close, and keep close the proof view if used

### ISSUE THREAD

**Issue by thomas-lamiaux** [coq-community/vscoq#876]
There is currently a button to close the proof view but it reopens constantly at each interaction which is not always wanted as some users:
- don't need it for what they are doing, e.g. meta-programming
- split their screen

Feature request: turn the close button in a open / close button, and if the window has been shut then it is not reopened unless the user presses the button

**Comment by TDiazT** [comment]
Where do you think this "open/close" button should be placed? (and look)
For instance, in the upper-right button list?
![image](https://github.com/user-attachments/assets/e59f6abd-862f-4917-b48f-e87e95034bac)

**Comment by TheoWinterhalter** [comment]
Maybe close could be an cross in the goal view? The open button I don't know, I feel like it should still open automatically if you step inside (but not around) a proof script. Otherwise it could be in the "Coq" menu?

**Comment by thomas-lamiaux** [comment]
I do not have all these buttons on my side. A simple button left to duplicating the script is perfectly. Similarly to what latex does.
![image](https://github.com/user-attachments/assets/81fc0f5a-27c9-4dd8-b124-737809637024)

**Comment by TheoWinterhalter** [comment]
I think that would be great!

**Comment by thomas-lamiaux** [comment]
Maybe it is too complicated but my idea would be that you would have a global option and a button, and if you decide to close it with the button then it does not reopen (disable the option for the file as long as the file is open)  until you click back on it ? 

I don't know how it works but I would like if I can select some files rather then all ?

**Comment by TheoWinterhalter** [comment]
I think the default behaviour should be that if you close it, it reopens when necessary (something to show). Otherwise it will be too confusing to users. Then an option for users that really want control to have a reopen button instead.

**Comment by thomas-lamiaux** [comment]
But then it must only open for a proof because right now it opens for every new definition / printing message.
In which case, can there be a simple shortcut to open and close maybe ?

**Comment by rtetley** [comment]
![Image](https://github.com/user-attachments/assets/738c6ba5-919e-43f5-ab4c-ef288f96e21d)

Si I tend to agree with @TheoWinterhalter on this one. This is how I implemented it, there is a simple option accessible from the vscoq congis. By default auto display is set to true. If the user opts out, there is a command, ```Coq: Display Proof View``` which is then available to re-open the proof view. The command is also made available through a button as showcased here.

**Comment by TheoWinterhalter** [comment]
That looks great.

**Comment by thomas-lamiaux** [comment]
Maybe I missexplained sth but it looks like great and what I had in mind

**Comment by thomas-lamiaux** [comment]
I have tested the functionality and it works well. However, it is a bit annoying to have to open and close by hand all the time. Could I suggest adding a simple shortcut to open and close it ?
