### ISSUE TITLE
Formatting results of Check

### ISSUE THREAD

**Issue by ybertot** [coq-community/vscoq#883]
There has been recent progress on the way goals are formatted, but the result of Check commands is still barely readable.

![Screenshot at 2024-09-02 12-56-14](https://github.com/user-attachments/assets/b2f014b3-8b95-4677-81b9-004f632f4e42)

**Comment by rtetley** [comment]
For context, is this in the goal view or in the query panel ?

**Comment by ybertot** [comment]
This appears in the query panel

**Comment by rtetley** [comment]
Okay ! You'll be happy to know this has been addressed. See #861.
It will make it in the next release !
