### ISSUE TITLE
Hover on qualifed names

### ISSUE THREAD

**Issue by ybertot** [coq-community/vscoq#884]
In a window with the following contents:

```
Module sandbox.

Lemma Earth_shadowing_result : 2 + 2 = 4.
Proof. reflexivity. Qed.

End sandbox.

Lemma unqualified_name : 2 + 2 = 4.
Proof. exact sandbox.Earth_shadowing_result. Qed.

Lemma simple_corollary : 2 <= 4.
Proof.
rewrite <- unqualified_name.

```
When hovering with the mouse on the theorem name "sandbox.Earth_shadowing_result" (8th line) no extra information is displayed.  When hovering with the mouse on the name unqualified_name, the type of this theorem appears.  The first hovering result should be the same as the second one.

**Comment by Durbatuluk1701** [comment]
I might also mention that along the same line, hover on a name that includes a single quote `'` is broken:
![Image](https://github.com/user-attachments/assets/beeaf42d-5987-4cf7-aa9b-f544ad1d2197)
