### ISSUE TITLE
VsCoq icon should only show up in sidebar when there are Coq files opened

### ISSUE THREAD

**Issue by RalfJung** [coq-community/vscoq#886]
Ever since I installed vscoq, the Coq icon shows up in the sidebar in all vscodium windows -- whether I do Rust, LaTeX, whatever, the Coq icon is always there:

![image](https://github.com/user-attachments/assets/7e31b5b1-24b9-455f-ab19-45dcf754fb33)

Other extensions generally hide themselves when they are not relevant for the current window (e.g. the LaTeX extension). Would be nice if vscoq could do the same. :)

**Comment by AmrElabbasy** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by RalfJung** [comment]
There also doesn't seem to be a way to use vscode settings to hide these icons per workspace, unfortunately.

**Comment by rtetley** [comment]
I am surprised it is not already the case :sweat: I will take care of it !
