### ISSUE TITLE
Goto definition does not work

### ISSUE THREAD

**Issue by CohenCyril** [coq-community/vscoq#9]
(e.g. ssrnum.v line 3522 big_andE)

**Comment by artagnon** [comment]
I think PG achieves jumping-to-definition via a `TAGS` file generated by [coqtags](https://github.com/ProofGeneral/PG/blob/master/coq/coqtags).

**Comment by Blaisorblade** [comment]
There's a plugin to support ctags, but doesn't seem to do etags: https://marketplace.visualstudio.com/items?itemName=jaydenlin.ctags-support.

**Comment by rtetley** [comment]
Closing in favor of #380
