### ISSUE TITLE
VsCoq running, installed on Windows WSL using OPAM, but can't run proof view

### ISSUE THREAD

**Issue by Mushow** [coq-community/vscoq#921]
Hi everyone, I tried using Alt+Down, Alt+Right, nothing works, whenever I run Ctrl+Shift+P and click on "Coq: Display Proof View", nothing shows up.

I already tried re-installing, enabling/disabling the extension and also restarted VS Code a couple of times.

```bash
mush@DESKTOP-VOKIC6H:~$ coqidetop.opt -v
The Coq Proof Assistant, version 8.20.0
compiled with OCaml 4.14.0
mush@DESKTOP-VOKIC6H:~$ 
```

Output:

```
[Toolchain] Searching for vscoqtop
[Toolchain] Found path: /home/mush/.opam/4.14.0/bin/coqtop
VsCoq initialised
```

Has any body run into this before?

**Comment by rtetley** [comment]
Can you tell me which version of the server / extension you have ? It seems like they are not in sync. This typically happens when the server has a higher version then the extension.

**Comment by Mushow** [comment]
![image](https://github.com/user-attachments/assets/382565da-5894-4351-abdd-c461c0409061)
VsCoq is on the latest version and the server I suppose is on 8.20?

**Comment by rtetley** [comment]
The server version is independent of the Coq-version. In the list above I don't see vscoq-language-server ?

**Comment by rtetley** [comment]
You should be notified that the server is not up to date... But I've got the feeling that the server launch failed before it could send version info... Could you check that ```vscoq-language-server``` is also on version 2.2.1 ?

**Comment by Mushow** [comment]
I do not find that package under opam list.

**Comment by Mushow** [comment]
vscoq-language-server 2.2.1       VSCoq language server

**Comment by rtetley** [comment]
> Hi everyone, I tried using Alt+Down, Alt+Right, nothing works, whenever I run Ctrl+Shift+P and click on "Coq: Display Proof View", nothing shows up.
> 
> I already tried re-installing, enabling/disabling the extension and also restarted VS Code a couple of times.
> 
> ```shell
> mush@DESKTOP-VOKIC6H:~$ coqidetop.opt -v
> The Coq Proof Assistant, version 8.20.0
> compiled with OCaml 4.14.0
> mush@DESKTOP-VOKIC6H:~$ 
> ```
> 
> Output:
> 
> ```
> [Toolchain] Searching for vscoqtop
> [Toolchain] Found path: /home/mush/.opam/4.14.0/bin/coqtop
> VsCoq initialised
> ```
> 
> Has any body run into this before?

Wait I just noticed that your log here says ```[Toolchain] Found path: /home/mush/.opam/4.14.0/bin/coqtop``` which is also suspicious... Did you perhaps set the path manually ? In which case could you just remove the setting or set it to ```/home/mush/.opam/4.14.0/bin/vscoqtop``` ?

**Comment by Mushow** [comment]
Now it works..  thanks.. I thought I had to set it manually. Thanks a lot!
