### ISSUE TITLE
No instructions on how to even use this extension.

### ISSUE THREAD

**Issue by crimsonalucard** [coq-community/vscoq#96]
There are two vscoqs available on the marketplace. The other one was updated 2017. This one is more recent. The problem is that this one does not have instructions on how to even use this extension.  

The only instructions I have found are currently located obscurely in the setup guide of the old repo. https://github.com/siegebell/vscoq/wiki/Setup.

These instructions should be on the ReadMe.

**Comment by andorp** [comment]
It worked for me out of the box. I have installed the required version of vscode and coq. I a newbie coq user and the only keybinding I use is the Alt+arrows to do the proof-steps. I agree that a description for key bindings, etc would be useful for newcomers to Coq.

**Comment by crimsonalucard** [comment]
Yes, I am one of those newcomers. Proof General is a huge hindrance due to the need to use emacs and CoqIDE actually starts to stutter and hang when the scratch file gets too large. 

Detailed instructions on how to use vscoq is a first step for popularizing Coq and formal methods in general.

**Comment by maximedenes** [comment]
Instructions added.
